### ISSUE TITLE
[FEAT] Dark mode

### ISSUE THREAD

**Issue by zarEclEC** [immuni-app/immuni-documentation#100]
**Describe the solution you'd like**
A dark mode version of the app

**Comment by immuniopensource** [comment]
Good morning @ArmeF97 and thanks for your issue. We don’t have any imminent plans to support dark mode in Immuni. As @Stenafo explained, user interactions with the app are limited as the app operates simply by being executed in the background. Dark mode is an important feature in apps that users interact with more frequently. We don’t believe that it warrants inclusion in Immuni. 
We're marking this issue as `wont-fix` and closing it consequentially. For any other question please open a new one, thank you!
