### ISSUE TITLE
[SUGGESTION] discussion platform + clearer roles on GitHub

### ISSUE THREAD

**Issue by fhtino** [immuni-app/immuni-documentation#101]
@immuniopensource 
To have a more useful and constructive issues tracking here on GitHub, please consider to:
- activate an external discussion board service. This would help to move general and verbose discussions to a proper place instead of using issues tracking for arguing.
- clarify roles of some people engaged in the analysis and discussion on the issues. Some users write like 'owner' of the code or, at least, as employee or collaborator of Bending Spoons. But this is not clear from their profiles and when asked, they do not reply. Example: #58

**Comment by iJaack** [comment]
Hi,
I also think this is critical in cleaning the issues list.

I suggest [Discourse](https://discourse.org/), that is open-source and can be easily deployed from GitHub Pages or with Netlify.
I could also help in moderating the discussions, as I’ve got experience in community management.
