### ISSUE TITLE
[FEAT] read only access to injected Rolling Proximity Identifier 

### ISSUE THREAD

**Issue by giovannicandotti** [immuni-app/immuni-documentation#103]
**Is your feature request related to a problem? Please describe it.**
It's not a problem, could be an usage enhancement

**Describe the solution you'd like**
A simple BLE scanner can collect Rolling Proximity Identifier of nearby people
May be that later on, some of these RPI are injected (TEKs, indeed, if I have understood properly) in the "public list" of dangerous contacts.
If it is possible to read these lists, and check against scanned RPI lists, it would be possible to signal the event also to people who had not Immuni installed or active, but where nearby in that period.
I think of huge company buildings: if someone was near the entrance/exit in a period when an RPI was logged, the company can advice also employees who have not the Immuni app active.

**Describe alternatives you've considered**
None

**Additional context**
Read only access needed to TEKs lists, and some info on how to recreate the RPI

**Comment by xelhark** [comment]
You are correct, the system does work the way you mentioned, except for this part:

> it’s possible to identify the period of a scanned RPI, and to signal to people nearby in that moment.

The Google/Apple APIs are specifically designed to avoid being able to trace back the source of the contact to a single TEK / RPI. Immuni does not have access to the specific TEK (or RPI) that triggered the contact notification, it only handles aggregate information, therefore it's impossible to narrow down the source of the contact to anything but a specific day.

What I meant in the previous message is that opening the APIs to a use case similar to what you are suggesting would also make the system more vulnerable to paparazzi attacks and similar issues.

**Comment by ivanvisconti** [comment]
> You are correct, the system does work the way you mentioned, except for this part:
> 
> > it’s possible to identify the period of a scanned RPI, and to signal to people nearby in that moment.
> 
> The Google/Apple APIs are specifically designed to avoid being able to trace back the source of the contact to a single TEK / RPI. Immuni does not have access to the specific TEK (or RPI) that triggered the contact notification, it only handles aggregate information, therefore it's impossible to narrow down the source of the contact to anything but a specific day.
> 
> What I meant in the previous message is that opening the APIs to a use case similar to what you are suggesting would also make the system more vulnerable to paparazzi attacks and similar issues.

Opening the API gives more powerful to the contact tracing system designer that can therefore end up with a better design (and also with a worse design obviously if the designer is not competent enough). For instance with access to the received RPIs one can heavily mitigate REPLAY attacks and can protect the privacy against paparazzi attacks; this has been shown already in the literature.

**Comment by immuniopensource** [comment]
Hi @giovannicandotti. We are soon going to close this issue. The proposed enhancement—which also has some additional risks, as previously pointed out by @xelhark—is beyond the scope of Immuni at present.

We trust that you appreciate the reasoning behind this decision. Should Immuni’s scope change in the future, we may reconsider this idea.
