### ISSUE TITLE
[Security] - Is the backend logging requests? If yes, how? Can we remove that?

### ISSUE THREAD

**Issue by lorenzosinisi** [immuni-app/immuni-documentation#106]
It is very common for backend services to log incoming requests including their IP, ISP provider, etc. 

Who and how can we guarantee that the backend is not storing this type of data when receiving requests? 

I would like to install the APP but I do not want the backend to log any info except what I want to send, so I would need some kind of clarification on the guarantee that the backend is not accidentally logging extra data that I do not want to provide

But good job for the source code, looks clean :)

**Comment by immuniopensource** [comment]
Hi @lorenzosinisi, the IP address of a mobile device is recorded by edge security appliances, to allow security analyses and investigations in case of an incident.
When a client request is sent from our edge to the internal backend -the one hosting Immuni services- a NAT operation is performed to mask the public address of the mobile device. The public address of a mobile device is not forwarded to the internal backend, which was also published as open source to increase transparency.
For users that would like to mask their IP addresses anyway when talking with the backend, they can use their VPN server of choice granted that the provider has servers in Italy or adjacent countries (land border only). Thank you for your question!

**Comment by lorenzosinisi** [comment]
Thank you for the clarification @immuniopensource , maybe this can be added to the documentation. Shall I create a PR?

**Comment by immuniopensource** [comment]
@lorenzosinisi that would be great and useful for many other users!

**Comment by lorenzosinisi** [comment]
Super, I will add it! :)
