### ISSUE TITLE
Epidemiological data shared without user's consent

### ISSUE THREAD

**Issue by vincenzoiovino** [immuni-app/immuni-documentation#11]
Hi,
the documentation says: 
"Upon assessing transmission risk. The upload may happen after the app has downloaded new keys from the server and assessed the transmission risk for the user, based on their recent contacts with SARS-CoV-2 positive users. In this case, the ensuing epidemiological data are uploaded automatically".
So the epidemiological data are AUTOMATICALLY uploaded without user's consent.
You cite some Ministerial decree. 
Can you point us the precise decree and article within that would prescribe users to automatically upload their epidemiological data without consent?

**Comment by iacopo** [comment]
Hopefully the user will have to express his consent just once, probably upon installing the app and accepting a disclaimer.
Thank god I don’t have to agree to gmail’s terms and conditions every time I send or receive an email...

**Comment by vincenzoiovino** [comment]
> Hopefully the user will have to express his consent just once, probably upon installing the app and accepting a disclaimer.
> Thank god I don’t have to agree to gmail’s terms and conditions every time I send or receive an email...

This is not what is written in the document. Are you from the Immuni's Team?

**Comment by vincenzoiovino** [comment]
> > Hopefully the user will have to express his consent just once, probably upon installing the app and accepting a disclaimer.
> > Thank god I don’t have to agree to gmail’s terms and conditions every time I send or receive an email...
> 
> This is not what is written in the document. Are you from the Immuni's Team?

If this were as you Say, this would be scaring. Users should be explicitly told that they are uploading private information.
The comparison with gmail's term Is imho misleading. You read emails every hour, but you are likely in touch with infected people much less frequently and epidemiological data are very sensitive information.

**Comment by vincenzoiovino** [comment]
> Thank god I don’t have to agree to gmail’s terms and conditions every time I send or receive an email...

If the system worked as you say, it would be scaring. 
Users should be explicitly informed that they are going to upload private information to an external server that can be subject to attacks (see what happened with INPS).
The comparison with gmail's term is imho misleading. You read emails every hour, but you are likely in touch with infected people much less frequently and epidemiological data are very sensitive information.

**Comment by gvdr** [comment]
The comparison with Gmail is absolutely out of place.

**Comment by iacopo** [comment]
> This is not what is written in the document. Are you from the Immuni's Team?

No I'm not.

Anyways this is not a mandatory app and I don't see any terms and conditions disclosed in the documentation yet. I think once the user is informed about when/how often his data are uploaded, he can make the call wether to accept the terms and use the app or decline and not use it.

This app is facing a huge challenge: its effectiveness depends on its user base and timeliness.
If, as you suggest, it should only upload data when the user decides to do so, timeliness is lost.
I don't see people willing to launch the app every x minutes to see if they have been exposed or not and then decide wether they want to share this information or not. If I agree to install the app, I most probably want it to run in background and do that for me automatically.

**Comment by vincenzoiovino** [comment]
> > This is not what is written in the document. Are you from the Immuni's Team?
> 
> No I'm not.
> 
> Anyways this is not a mandatory app and I don't see any terms and conditions disclosed in the documentation yet. I think once the user is informed about when/how often his data are uploaded, he can make the call wether to accept the terms and use the app or decline and not use it.

I do not see why the fact that the app is not mandatory affects or mitigates this issue.
As it is written in the document, the data is AUTOMATICALLY uploaded. If it were the case that since the moment the user gives the consent, for instance at installation time, then the user does not longer need to give consent for a so sensitive information, it would be in my opinion a serious threat to user's privacy.
> 
> This app is facing a huge challenge: its effectiveness depends on its user base and timeliness.
> If, as you suggest, it should only upload data when the user decides to do so, timeliness is lost.
> I don't see people willing to launch the app every x minutes to see if they have been exposed or not and then decide wether they want to share this information or not. If I agree to install the app, I most probably want it to run in background and do that for me automatically.

The argument of timeliness does not add anything to this discussion. You can use this argument for ANY issue opened on this repository. you can always reply that, because of time, we need to rush and we cannot take in account issues properly.
Here people give suggestions independently and irrespective of the fact that Immuni will release an insecure or bad app because they had no time to solve the issues, it is enough that people are publicly informed "the app is insecure and does not take in account serious issues (with the list) but we urged to release the app".

**Comment by iacopo** [comment]
I meant timeliness as in: sharing contact data as soon as possible, without requiring the user to open the app and decide to upload it. Not as in: let's rush releasing the app no matter what.

**Comment by vincenzoiovino** [comment]
> I meant timeliness as in: sharing contact data as soon as possible, without requiring the user to open the app and decide to upload it. Not as in: let's rush releasing the app no matter what.

In this case I have already responded. 
The discussion in this issue refers to the event in which the user has been in contact with an another infected user.  This event is not so frequent so I do not see problems of timeliness. If the user is at-risk it is him/her  right to give explicit consent on what to upload.

**Comment by iacopo** [comment]
I'm not sure I'm getting the point, so let me synthesise:

1. The app detects a potential contact between user A and user B.
2. Later user A get in contact with users XYZ
3. Later user B gets tested positive to covid-19 and uploads that information to the system with the help of a helthcare op.
4. At this time, when user A's application gets the list, the app informs user A has been exposed.

What we are debating on is if, in this case, the app should upload A's contact list immediately thanks to a previously given consent, or if it should ask the user explicit consent every time this case occurs.

In my opinion step 5 is: the app uploads A's contact list to the server immediately so that users XYZ know they've been exposed to a potentially positive person. Probably assigning a rating value to the users or using whatever the app’s risk model algorithm defines.

Otherwise, if this kind of information is only sent if/when user A decides to do so, I don't see the point in using the app, because it would be effective in detecting 1st level contacts only.

**Comment by AndreazLattmann** [comment]
Just put a switch on the data that you authorize/do not authorize to send.  
I don't agree on sending them automatically, it's against privacy and GDPR.  
I have the right that if one morning I wake up pissed off to be able to decide the data that I want to share or not (the law says).
It's up to the developers to do a switch!

**Comment by AndreazLattmann** [comment]
From a legal point of view, the possibility should always be given to decide whether to give or not give consent. 
I don't think it is impossible to insert a switch in the app configuration to give or deny consent.

**Comment by macteo** [comment]
On iOS 13.5 beta a system level toggle let the user enable or disable explicitly the exposure notification service on the phone. The app has access to this feature switch. The A/G framework doesn't return the epidemiological data to the app if the toggle is disabled, so the upload won't occur.

It's not clear if such system level toggle will exists on Android.

**Comment by amefad** [comment]
I agree with @vincenzoiovino 
The documentation says there are 2 kinds of data uploaded to server:
1. list of recent Temp ID 
2. other epimediological data

the data at 1. are clearly understood by user who can consent the upload when he or she is found positive (why consent on installation? This upload could even never happen)
The data in 2. I'm not able to understand clearly what are made of... (there's the province of domicile that worth almost nothing cause the user can declare other than the truth ) this need more explanation and a specific consent by user.

**Comment by immuniopensource** [comment]
Good morning @vincenzoiovino, as described in detail in [Privacy-Preserving Analytics](https://github.com/immuni-app/immuni-documentation/blob/master/Privacy-Preserving%20Analytics.md#epidemiological-info), there are two types of information that Immuni collects and uploads: Epidemiological Info and Operational Info. 

Epidemiological Info is a set of Exposure Detection Summaries and Exposure Info provided by the A/G Framework when it has detected a Risky Exposure. This info is only uploaded if and when the user has tested positive for SARS-CoV-2, and only in the context of TEKs upload. As the TEKs upload is a process that has to be manually performed by the user, Epidemiological Info cannot be uploaded automatically. 

Operational Info, on the other hand, is uploaded automatically, following the criteria as described in the documentation. Other than some information related to the status of the App, Immuni can only share whether the user was notified of a Risky Exposure after the previous Exposure Detection, and the date on which the last Risky Exposure took place. This represents the minimum amount of information that the National Health Service needs to monitor Immuni. The Operational Info contains no information about the device that sent it, and the risk of an attacker inferring any sensitive information is mitigated through multiple measures laid out in [Traffic Analysis Mitigation](https://github.com/immuni-app/immuni-documentation/blob/master/Traffic%20Analysis%20Mitigation.md).


The data collected and their purposes is specified in the Privacy Notice, which all the users must accept before using Immuni.
