### ISSUE TITLE
Comparisons between random identifiers

### ISSUE THREAD

**Issue by Sim98B** [immuni-app/immuni-documentation#115]
Hi everyone, I have a question regarding the comparison between the random identifiers collected and those indicated as positive to the virus, I noticed that since June 6 on my iphone (iOS 13.5.1) comparisons appeared between the identifiers collected and those theoretically present on the positive server but these comparisons were not carried out in the next two days. I would like to know how often Immuni makes these comparisons and if special conditions are needed to make the comparisons. Thank you all.

**Comment by ItsFiloHere** [comment]
I confronti dovrebbero avvenire su base giornaliera, e comunque per eseguirli è necessario essere connessi alla rete. Immuni scarica dal server gli ID positivi e li confronta, in locale, con quelli raccolti

**Comment by Sim98B** [comment]
Grazie mille filioro, si ho presente come vengono effettuati i confronti ma non capisco come mai ne siano stati effettuati alcuni un giorno per poi interromperli; o almeno il mio log dei controlli non viene più aggiornato cosa che comunque dovrebbe avvenire giornalmente

**Comment by lrsb** [comment]
Immuni fornisce ad iOS gli id delle persone risultate positive se esse decidono di caricare il loro id.
Se negli ultimi giorni non sono avvenuti confronti vuol dire che non sono state caricate nuove chiavi.
Puoi verificare il chunk index attuale qui: https://get.immuni.gov.it/v1/keys/index

**Comment by vi-enne** [comment]
> Immuni fornisce ad iOS gli id delle persone risultate positive se esse decidono di caricare il loro id.
> Se negli ultimi giorni non sono avvenuti confronti vuol dire che non sono state caricate nuove chiavi.
> Puoi verificare il chunk index attuale qui: https://get.immuni.gov.it/v1/keys/index

Mi inserisco nella conversazione per porre una domanda.
Se quanto affermato e' vero, questo vuol dire che sapendo che una persona e' risultata positiva e che nessuna nuova chiave e' stata caricata:
- la persona positiva non usa Immuni 
oppure
- la persona positiva usa Immuni ma ha deciso di non condividere le sue chiavi.

Mi sbaglio?

Grazie!

**Comment by lrsb** [comment]
> > Immuni fornisce ad iOS gli id delle persone risultate positive se esse decidono di caricare il loro id.
> > Se negli ultimi giorni non sono avvenuti confronti vuol dire che non sono state caricate nuove chiavi.
> > Puoi verificare il chunk index attuale qui: https://get.immuni.gov.it/v1/keys/index
> 
> Mi inserisco nella conversazione per porre una domanda.
> Se quanto affermato e' vero, questo vuol dire che sapendo che una persona e' risultata positiva e che nessuna nuova chiave e' stata caricata:
> 
> * la persona positiva non usa Immuni
>   oppure
> * la persona positiva usa Immuni ma ha deciso di non condividere le sue chiavi.
> 
> Mi sbaglio?
> 
> Grazie!

In linea teorica si.
In pratica, considerando che è ancora in fase di test, ci potrebbero essere altri motivi.
Non essendo personalmente coinvolto nel progetto ti consiglio di provare a chiedere qui: cittadini@immuni.italia.it

**Comment by Sim98B** [comment]
Ripropongo la domanda all’inizio della conversazione in vista dei primi caricamenti ufficiali delle chiavi dei dispositivi, dopo i quali il mio dispositivo non ha ancora effettuato controlli. Rimangono ancora i 3 controlli risalenti al 6 giugno per un totale di 5 chiavi ma non vi è traccia di queste chiavi. Che siano le stesse già controllate il 6 giugno? Chiedo anche se sia normale che non vengano effettuati controlli per il fatto di non trovarsi nella regione nella quale sono state caricate le chiavi.
Grazie mille

**Comment by ItsFiloHere** [comment]
Domani, alle 10:30 sul Reddit r/italy, ci sarà un Ask Me Anything con il
team di BS su Immuni, prova a chiedere domani! 😀

Il Dom 14 Giu 2020, 16:35 Sim98B <notifications@github.com> ha scritto:

**Comment by ItsFiloHere** [comment]
In ogni caso, l'ultimo controllo risale all'11 giugno

**Comment by lrsb** [comment]
> Ripropongo la domanda all’inizio della conversazione in vista dei primi caricamenti ufficiali delle chiavi dei dispositivi, dopo i quali il mio dispositivo non ha ancora effettuato controlli. Rimangono ancora i 3 controlli risalenti al 6 giugno per un totale di 5 chiavi ma non vi è traccia di queste chiavi. Che siano le stesse già controllate il 6 giugno? Chiedo anche se sia normale che non vengano effettuati controlli per il fatto di non trovarsi nella regione nella quale sono state caricate le chiavi.
> 
> Grazie mille


Riguardo al primo punto non posso darti una risposta certa, ho notato anch’io questa “discrepanza”. Visto che si parla di tre persone è verosimile che quelle chiavi siano nel chunk numero 2 (del 6 giugno appunto).
Per avere una risposta certa segui il consiglio di @filioro

Riguardo il secondo punto, invece, la richiesta della provincia da parte di immuni ha puro carattere epidemiologico. Non viene, e non ha senso che venga, utilizzata durante la corrispondenza delle chiavi in quanto:
- Il soggetto si sarebbe potuto spostare in tutta Italia
- La resistenza alle collisioni tra chiavi deve essere assicurata dall’algoritmo e non dalla posizione geografica

**Comment by lrsb** [comment]
> In ogni caso, l'ultimo controllo risale all'11 giugno

Quello che ha detto @Sim98B è corretto, l’ultimo controllo risale al 6 giugno

**Comment by ItsFiloHere** [comment]
> > In ogni caso, l'ultimo controllo risale all'11 giugno
> 
> Quello che ha detto @Sim98B è corretto, l’ultimo controllo risale al 6 giugno

Nono, il mio smartphone ha effettuato l'ultimo controllo alle 14:19 dell'11 giugno...

**Comment by lrsb** [comment]
Questi sono i controlli che sono stati fatti:
```json
{
  "ExportVersion" : 1,
  "ExposureChecks" : [
    {
      "Hash" : "9C8D0CF49F55EFCBBC760446392060E3CA93BFB5FECEEB160D81FED52386C258",
      "RandomIDCount" : 1,
      "MatchCount" : 0,
      "DataSource" : "it.ministerodellasalute.immuni",
      "Timestamp" : "2020-06-06 14:55:12 +0200"
    },
    {
      "Hash" : "F0DDE552498491C2C21BEFCB34F45025B92CB7C8E398325D12BB196CD4C9441C",
      "RandomIDCount" : 3,
      "MatchCount" : 0,
      "DataSource" : "it.ministerodellasalute.immuni",
      "Timestamp" : "2020-06-06 14:55:12 +0200"
    },
    {
      "Hash" : "4E2B79C5E84A83B2E115661A07101CB575DD3BB835A3403B76B33A815D4F1339",
      "RandomIDCount" : 1,
      "MatchCount" : 0,
      "DataSource" : "it.ministerodellasalute.immuni",
      "Timestamp" : "2020-06-06 20:19:05 +0200"
    }
  ]
}
```

Puoi verificare che i chuck pubblicati sono tre finora: https://get.immuni.gov.it/v1/keys/index

Hai reinstallato l'app? Hai sempre il telefono connesso?

**Comment by Sim98B** [comment]
@lrsb il telefono è sempre connesso, alternando connessione dati e Wi-Fi in caso di spostamenti, e controllo giornalmente le richieste di controllo del log di esposizione. Non ho provato a disinstallare l’app ma disinstalla sola non perderei i contatti avuti in precedenza? Grazie mille

**Comment by lrsb** [comment]
> @lrsb il telefono è sempre connesso, alternando connessione dati e Wi-Fi in caso di spostamenti, e controllo giornalmente le richieste di controllo del log di esposizione. Non ho provato a disinstallare l’app ma disinstalla sola non perderei i contatti avuti in precedenza? Grazie mille

La mia era una risposta a @filioro . I tuoi controlli sono gli stessi che ho anch’io.
Non saprei dirti, con sicurezza, se cancellando l’app vengano cancellate anche le chiavi raccolte.
In generale cancellare l’app credo sia come disattivare la raccolta e che quindi, se dovessi reinstallarla entro 14 gg, potresti essere avvertito di eventuali contatti.

**Comment by ItsFiloHere** [comment]
Il telefono è sempre connesso, mi sembra che nei giorni attorno all'8 avevo resettato l'app :)

**Comment by Sim98B** [comment]
> Il telefono è sempre connesso, mi sembra che nei giorni attorno all'8 avevo resettato l'app :)

Resettato l’app? A cosa ti riferisci?

**Comment by ItsFiloHere** [comment]
Ho cancellato i dati (non i codici raccolti) dalle impostazioni del
cellulare

Il Dom 14 Giu 2020, 20:56 Sim98B <notifications@github.com> ha scritto:

**Comment by immuniopensource** [comment]
Buongiorno @Sim98B, come spiegato da altri nel thread, il numero di confronti che vengono effettuati e registrati dal sistema operativo in “Exposure Checks” dipende dal caricamento delle chiavi crittografiche da parte degli utenti risultati positivi. Non è pertanto garantito che vengano effettuati dei confronti ogni giorno. L’applicazione verifica comunque regolarmente la presenze di nuove chiavi e, nel caso ve ne siano, effettua il confronto.
A seguito di una reinstallazione dell’app, vengono già da subito scaricate tutte le chiavi più recenti ed effettuati i relativi confronti. Tuttavia, nel caso di dispositivi Android, le chiavi crittografiche precedentemente registrate vengono cancellate in fase di disinstallazione dell’app se non ve ne sono altre installate che usano l’A/G Framework. In questi casi risulta pertanto impossibile venire avvertiti di eventuali contatti in giorni antecedenti alla reinstallazione dell’app. Le chiavi crittografiche vengono invece preservate a seguito della disinstallazione dell’app sui dispositivi con iOS.
Se dovessi avere altri dubbi, rimaniamo a disposizione, grazie.
