### ISSUE TITLE
Interferenza con bluetooth Android Auto

### ISSUE THREAD

**Issue by palmirani** [immuni-app/immuni-documentation#117]
Ho installato Immuni, sono residente a Bologna, Emilia-Romagna. 
Il cellulare è Galaxy A3, Google Play Services 20.18.17, versione Android 8.0.0. 
Se collego il cellulare mediante cavo alla macchina Kia e si tenta di utilizzare Adroid Auto il telefono non viene rintracciato come se il bluetooth fosse occupato. L'errore è "telefono non rintracciato". Anche disattivando l'app Immuni il teleofono non si ricollega alla autovettura. Ho dovuto disinstallare Immuni per poter usare Google Map dal telefono in connessione con i dispositivi dell'auto.
L'ho poi re-installata.

**Comment by immuniopensource** [comment]
Buongiorno @palmirani e grazie per la segnalazione. Benché la reinstallazione di Immuni abbia permesso di risolvere (temporaneamente?) il problema, esso sembrerebbe essere causato non direttamente dall’app, quanto dal modulo Bluetooth, utilizzato sia da Immuni che da Android Auto. Non avendo Immuni alcun controllo su tale modulo, non abbiamo modo di investigare in dettaglio o risolvere il problema che hai riscontrato.
Se dovessi avere altre domande a riguardo restiamo a disposizione, per il momento chiudiamo questa issue, grazie!
