### ISSUE TITLE
Interferenza con dispositivi bluetooth LE su macbook

### ISSUE THREAD

**Issue by RickyLeRoi** [immuni-app/immuni-documentation#118]
hardware coinvolto:
- notebook: Macbook Pro 16" 2019 - Catalina 10.15.5
- smartphone: Honor 10 (COL-L29)
- mouse: Logitech MX Master 2s (in BT LE)
- cuffie: Sennheiser HD 350BT (in BT)

cosa accade:
Ogni tot minuti (non quantificati con esattezza), il mouse BT smette di comunicare con il macbook.
Quando accade, tra i dispositivi BT attualmente connessi se ne trovano due, il mouse e uno chiamato con un MAC address (simile al BT address del mio smartphone per 4 caratteri su 12 ma credo non sia influente). Disconnesso il secondo dispositivo, il mouse riprende a funzionare correttamente.
Disabilitando il BT dallo smartphone o disattivando il servizio Immuni, il problema non si verifica più.
Tutto ciò non influisce minimamente sulle cuffie che funzionano con BT 5.0 ma non LE.

<img width="215" alt="Schermata 2020-06-09 alle 19 52 30" src="https://user-images.githubusercontent.com/14819069/84182521-d260f600-aa8a-11ea-94cb-e96228736b48.png">
<img width="302" alt="Schermata 2020-06-09 alle 19 53 25" src="https://user-images.githubusercontent.com/14819069/84182566-e73d8980-aa8a-11ea-92ab-d1ac981b80d3.png">

**Comment by amreo** [comment]
Cosa succede se spegni le cuffie? Riscontri lo stesso problema?

**Comment by RickyLeRoi** [comment]
si, stesso problema, nello screenshot anzi le cuffie non erano collegate, scusa ho dimenticato ad indicarlo.

**Comment by immuniopensource** [comment]
Ti ringraziamo per la segnalazione @RickyLeRoi. Sembrerebbe tuttavia che il problema da te riscontrato non sia strettamente legato a Immuni, quanto invece a come il tuo notebook o il tuo mouse gestiscono la loro connessione tramite BLE. Non possiamo pertanto intervenire in alcun modo per poter risolvere il problema. 
Restiamo a disposizione, grazie.
