### ISSUE TITLE
Improve documentation with FAQ on A/G framework issues

### ISSUE THREAD

**Issue by vi-enne** [immuni-app/immuni-documentation#120]
Hi,
I notice that a big part of the opened issues are relative to the A/G framework and not specifically to the Immuni App.
(The last one as an example is #119)

While I understand these issues are problematic also for Immuni, the developers have no control over them: the app is thought to be build around the A/G framework, otherwise it will be another app.

I suggest then to create a section of the documentation collecting the known issue related to the A/G framework.

This will give clarity, avoid the creation of out of scope issues, and improve honesty on the unsolvable (by the developers) privacy issues.

Thank you,
Vittorio

**Comment by pdehaye** [comment]
This would indeed be very welcome. 

That comment is also applicable to #124.
