### ISSUE TITLE
[QUESTION] How is the app using the region and province information?

### ISSUE THREAD

**Issue by gianvitofanelli** [immuni-app/immuni-documentation#123]
Hi everyone,
it is not clear to me and some of my friends how Immuni is using information regarding the region and the province. Should we change the information if we move across the country?

Thank you

**Comment by gianvitofanelli** [comment]
Is there anybody out there?

**Comment by djechelon** [comment]
@gianvitofanelli I am no official source, and unfortunately I couldn't find the press source in the last 5 minutes to link.

The idea is that the province of residency has only statistical value, and there is a recommendation (again, I can't find the source) about it.

First, the residency information is only aggregated with no connection to the source of hashes, when those are uploaded. The idea is that an upcoming data analysis framework will help the health authority display statistics and possibly plan medical resources with the evolvings of the pandemic.

The recommendation that I have read and that, again, I can't find again, is the following:

- If you are going to move to another province for a short period of time, including remote working or short vacations, you **should not** change the province in Immuni
- If you are going to move to another province for a longer period of time, e.g. you want to perform smart working from your summer house, **and** if you expect to have medical assistance (general practicioner...) in the other province, then you **should change** the province of residency, regardless of whether you register at the town office for official residency

In the latter case, it is advisable that, should you be found positive in region "B", and if you and your potential contacts will receive medical care in region "B", region "B"'s health authorities received quality statistics about the potential number of cases.

My comment: that's a usability issue. You can ask a user "where do you live" and get a prompt response. Imagine if you ask user "where do you expect to receive medical care?", most people will close the application instantly 😆

**Comment by gianvitofanelli** [comment]
Thank you very much,
I have updated my province as I’m working remotely from my summer house :)

**Comment by immuniteam** [comment]
Hi @gianvitofanelli , thanks for the issue.
The information on the province of domicile can be used to monitor the development of the epidemic at the provincial level. Being able to have an estimate, albeit deriving from an approximation of the number of users at risk day by day in the various Italian provinces, allows the National Health Service to best allocate its resources to face the epidemic. Our advice is to change the province only if the journey lasts many days and is always in the same place. Let us know if you need further details! For the moment we close the issue.
