### ISSUE TITLE
On iOS, what is the meaning of "Numero chiavi fornite" and "Numero chiavi corrispondenti"?

### ISSUE THREAD

**Issue by alessandro-gentilini** [immuni-app/immuni-documentation#125]
I have read https://github.com/immuni-app/immuni-documentation/blob/master/CONTRIBUTING.md but I do not know whether my question is related to "the Apple & Google protocol".

On iOS, if you follow this path *Impostazioni → Immuni → Impostazioni raccolta log di esposizione al COVID-19 → Controlli esposizione* you will get a list of date and time, for example `23 giu 2020, 01:13`, clicking on it you will get the following table:

*first column*|*second column*
---------------|-------------------------
Data e ora | 23 giu 2020, 01:13
Numero chiavi fornite | *n*
Numero chiavi corrispondenti | *m*
Fonte dati | Immuni

where *n* and *m* are two non negative integers.

What is the meaning of *Numero chiavi fornite*?

What is the meaning of *Numero chiavi corrispondenti*?

I was thinking that, maybe, if these integers were available to Immuni then they could be used to create a richer feedback to the user apart from the terse "Servizio attivo"; I think this is related to https://github.com/immuni-app/immuni-documentation/issues/63

If this issue is related to "the Apple & Google protocol", where can I find an answer, possibly in Italian? These URLs https://www.google.com/search?q=%22Numero+chiavi+fornite%22+site%3Aapple.com or https://www.google.com/search?q=%22Numero+chiavi+corrispondenti%22+site%3Aapple.com gives me no useful answers.

Thank you for your help.

**Comment by ItsFiloHere** [comment]
Hi! "Numero chiavi fornite" is the number of the keys that Immuni gives to iOS (the keys on the server) and "Numero chiavi corrispondenti" is the number of positive matches between the keys on your device and the keys on Immuni's server.

**Comment by alessandro-gentilini** [comment]
@filioro Thank you, do you have an authoritative source for your statement?

**Comment by ItsFiloHere** [comment]
> @filioro Thank you, do you have an authoritative source for your statement?

At the moment no. Let's wait for more informations.

**Comment by immuniopensource** [comment]
Good morning @alessandro-gentilini, @filioro’s answer is correct. Numero chiavi fornite (Provided Key Count) is the number of keys included in the chunk, while Numero chiavi corrispondenti (Matched Key Count) is the number of corresponding matches the App has found.

Both numbers are available, but we don’t think that there is much benefit in displaying them within the App. For example, Matched Key Count provides no additional information beyond that which the user already has. It is either zero, or the Exposure Notification framework already warned them about a possible Risky Exposure.

Let us know if you have any other doubts, thank you.

**Comment by zenodallavalle** [comment]
> @immuniopensource: It is either zero, or the Exposure Notification framework already warned them about a possible Risky Exposure

I was checking tonight and I saw something in contrast with your statement. Here you can see ![image](https://user-images.githubusercontent.com/48842588/109071673-524fee80-76f4-11eb-9365-13a1f2b87e4b.jpeg) Matched Key Count = 1 but I didn't receive any notification. Maybe some criteria (like time exposure threshold, etc) are applied between the match and the notification.

**Comment by TheConfax** [comment]
@immuniopensource @alessandro-gentilini 
Ho controllato per caso nelle impostazioni di iOS e vedo 2 chiavi corrispondenti per una data, 1 chiave corrispondente per un'altra data, ma non ho mai ricevuto nessuna notifica né immuni mi mostra qualcosa a riguardo. Cosa significa?
