### ISSUE TITLE
Inserire una schermata informativa su quali parametri utilizza l'algoritmo

### ISSUE THREAD

**Issue by ItsFiloHere** [immuni-app/immuni-documentation#126]
Sarebbe utile inserire, in fase di setup, una schermata informativa che indica:
- I parametri utilizzati dell'algoritmo dell'app
- Che il rischio potrebbe essere sovrastimato in quanto Immuni non sa se indossiamo un DPI o se c'è un plexiglass.

Grazie

**Comment by immuniopensource** [comment]
Innanzitutto, grazie per i suggerimenti @filioro. 
In tutta franchezza, vediamo poco valore nel mostrare i parametri utilizzati dall’algoritmo all’interno dell’app, specialmente durante la fase di setup. Si tratta di un dettaglio prettamente tecnico, che aggiunge poco valore per la maggior parte degli utenti e rischia al contrario di confonderli in una fase molto delicata del processo. I parametri di configurazione restano comunque sempre accessibili, così come tutto il codice sorgente, a chiunque voglia esaminarli. Più che il valore in sé dei parametri, riteniamo tuttavia importante che l’algoritmo approssimi al meglio i requisiti del Ministero della Salute, che considera un’esposizione a rischio se di durata superiore a 15 minuti e a una distanza inferiore a 2 metri. Questo perché nonostante possa risultare necessario regolare nuovamente i valori dei parametri a seguito di ri-calibrazioni effettuate da Apple e Google, il requisito rimane comunque invariato.
L’osservazione che porti rispetto al rischio in caso di DPI ha sicuramente del merito. Ci teniamo a ribadire che Immuni si limita a notificare l’utente di una precedente esposizione a un utente potenzialmente contagioso ma non entra mai nel merito di quantificare il rischio di contrazione del virus. Questo perché ci sono diversi fattori che concorrono a determinare il rischio di contagio (tra cui i DPI giustamente menzionati) che Immuni non può ovviamente conoscere. Non possiamo affermare pertanto che il rischio è sovrastimato, in quanto Immuni non fornisce alcuna stima del rischio di contagio. Il fatto invece che sia avvenuto un contatto, indipendentemente dall’incertezza sull’effettiva distanza relativa tra i due utenti, resta un dato oggettivo, indipendentemente da DPI, contagiosità dell’utente o qualunque altro fattore esogeno che possa determinare un avvenuto contagio. Anche in considerazione di un potenziale falso senso di sicurezza che potrebbe fornire, riteniamo pertanto poco utile mostrare una schermata informativa dedicata a questo tema all’utente.

Restiamo a disposizione, grazie molte!
