### ISSUE TITLE
App Immuni non scarica nulla...?

### ISSUE THREAD

**Issue by djechelon** [immuni-app/immuni-documentation#128]
(Questo post sta per essere modificato)
<strike>Non è propriamente un bug report, ma secondo me una issue su cui approfondire.</strike>

Nessuno dei miei dispositivi ha mai ricevuto chiavi di prossimità da Immuni, come se non fosse mai stato riportato alcun positivo alle autorità sanitarie.

Prova eseguita su due dispositivi, come da indicazioni di seguito nel post

**Dispositivo 1**
Device. Pixel 3XL "crosshatch"
OS. Android 10 (patch luglio) + Magisk
Play Services:  20.24.14 (120400-319035315)

**Dispositovo 2**
Device. Nokia 7.1
OS. Android 10 stock con patch di giugno, aggiornato da Nokia regolarmente

Andando mediante il pannello di controllo Google (`Impostazioni` -> `Google` -> `Notifica esposizione Covid 19` -> `Controlli esposizione`) vedo una lista di scarichi dei codici casuali (12 controlli negli ultimi 14 giorni).

Tutte le schermate, ne riporto una, segnalano zero chiavi e zero corrispondenze

![Screenshot_20200709-161614](https://user-images.githubusercontent.com/3042285/87051954-8aa3ca80-c200-11ea-988c-33d3030d954a.png)

La schermata è di Android, **non** di Immuni.

Dato che [fonti di stampa](https://www.lagazzettadelmezzogiorno.it/news/bari/1230324/bari-prigioniera-di-immuni-costretta-alla-quarantena-dall-app-ma-non-mi-fanno-il-tampone.html) riportano che _una_ persona è stata segnalata dalla app come potenziale positiva, mi sarei aspettato che almeno nei vari scarichi avrei trovato almeno una chiave, poi ovvio che se non sono stato a contatto con quella persona (non la donna intervistata, quello/a che è risultato positivo) non c'è corrispondenza.

Ho Immuni dal primo giorno di uscita su Play Store. <strike>Ho fatto installare Immuni ai miei familiari, quindi i nostri device dovrebbero certamente aver accumulato un gran numero di chiavi da giugno. Nessuno è mai stato tamponato, nè tantomeno risultato positivo ovviamente.</strike> (c'entra zero)

Questa issue solo per segnalare che tutti i miei scarichi di chiavi temporanee riportano zero. Mi sembra strano. Info?

**Comment by filippogasbarro** [comment]
Ciao,
in realtà Immuni funziona e circa ogni giorno (lo puoi vedere dal framework di google nella dicitura "ultimo controllo esposizione") fa dei controlli per verificare se ci sono dei "numeri di chiavi fornite" (ossia tutte le chiavi fornite da un positivo). Nel "numero corrispondenze" sono le chiavi dal contatto positivo ed il tuo telefono le ha "viste" con il bluetooth.

Essendo l'articolo del 20 giugno, le chiavi inviate, ad oggi, non le potrai più vedere essendo segnalate più di 2 settimane fa

**Comment by djechelon** [comment]
Ok, volevo capire se è normale che anche ad oggi 14 luglio le chiavi dei positivi (numero chiavi fornite) restino sempre a zero su tutti i controlli pregressi degli ultimi 14 giorni (da notare keyCount sempre zero, matchesCount zero vuol dire che sono stato attento)

(Non mi fa allegare il file)

```
[
    {
       "timestamp":"4 luglio 2020 00:35",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"4 luglio 2020 22:02",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"8 luglio 2020 20:37",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"30 giugno 2020 15:02",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"30 giugno 2020 19:04",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"13 luglio 2020 18:39",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"2 luglio 2020 16:46",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"6 luglio 2020 21:17",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"1 luglio 2020 20:05",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 },
    {
       "timestamp":"3 luglio 2020 20:35",
       "keyCount":0,
       "matchesCount":0,
       "appName":"Immuni",
       "hash":""
    
 }
 ]
```

**Comment by djechelon** [comment]
Se questo è normale si può chiudere

**Comment by filippogasbarro** [comment]
Si, il comportamento è normale.
Fortunatamente non sono stati segnali casi positivi con immuni in questi 14 giorni

**Comment by alessandro-gentilini** [comment]
@filippogasbarro io ho una entry con `Data e ora` = `13 lug 2020, 17:59` e `numero chiavi fonite`=`7` quindi a me lo `0` che ha @djechelon in corrispondenza di `"timestamp":"13 luglio 2020 18:39"` mi sembra strano... anche per questi motivi avevo aperto https://github.com/immuni-app/immuni-documentation/issues/125

**Comment by lmasellis** [comment]
> Si, il comportamento è normale.
> Fortunatamente non sono stati segnali casi positivi con immuni in questi 14 giorni

Se il fatto che non siano stati segnalati casi positivi tramite Immuni sia una "fortuna" è quantomeno discutibile. A me sembra più un segno evidente che il sistema non stia funzionando (o perché la gente non la usa, o perché le autorità sanitarie non invitano a fare la segnalazione dopo il test).

Comunque che non ci siamo casi positivi da 14 giorni (il che giustificherebbe l'indicazione di zero chiavi da parte di Google Play Services) non mi torna. Il backend, seppur solo ogni qualche giorno e con poche chiavi, continua a servire archivi di chiavi. L'ultimo, sequenziale n. 23, ha un end timestamp pari a 1594220404, cioè Wed Jul  8 17:00:04 CEST 2020, e contiene 7 chiavi. Eppure l'ultimo controllo riportato da Google Play Services, datato 13 luglio, viene indicato con "Numero di chiavi" pari a zero (come peraltro tutti gli altri controlli precedenti). Qualcosa non torna.

**Comment by filippogasbarro** [comment]
Allora lasciamola aperta la problematica.
io ho una entry del 14 luglio alle 9 e ho 0 numero di chiavi.

"Il backend, seppur solo ogni qualche giorno e con poche chiavi, continua a servire archivi di chiavi. L'ultimo, sequenziale n. 23, ha un end timestamp pari a 1594220404, cioè Wed Jul 8 17:00:04 CEST 2020, e contiene 7 chiavi"
Da dove vedi questi dati?

**Comment by lmasellis** [comment]
> "Il backend, seppur solo ogni qualche giorno e con poche chiavi, continua a servire archivi di chiavi. L'ultimo, sequenziale n. 23, ha un end timestamp pari a 1594220404, cioè Wed Jul 8 17:00:04 CEST 2020, e contiene 7 chiavi"
> Da dove vedi questi dati?

Scaricando e decodificando i file serviti dal backend secondo le specifiche di Google, ad es. https://get.immuni.gov.it/v1/keys/23

Ne avevo parlato anche qui: https://github.com/immuni-app/immuni-app-android/issues/233
Il protocollo assume che in ogni file vengano accorpati numerosi utenti risultati positivi, e per ogni utente tutte le chiavi associate per il periodo considerato. Visto che i file serviti finora includono circa 7/8 chiavi ciascuno, e in ogni file mettendole in ordine di timestamp formano sempre una sequenza completa con incremento pari a 144 (cioè l'intervallo di rotazione delle chiavi), è realistico pensare che ciascuno dei file serviti finora sia riferito ad un singolo utente. E cioè che finora il sistema Immuni abbia segnalato solo 23 positività.

Tra l'altro, questo costituirebbe un problema in termini di anonimato. Il protocollo Google/Apple assume che le chiavi servite in ogni file si riferiscano ad una molteplicità di utenti, e che basti mescolarle (come raccomanda la specifica) per evitare che più chiavi possano essere associate ad un utente. Distribuire file con la sequenza completa riferita ad un singolo utente permette, conoscendo l'identità di una singola chiave, di associarla a tutte le altre nella sequenza.

**Comment by alessandro-gentilini** [comment]
@Imasellis ti posso confermare che su iOS del mio telefono io vedo `Data e ora = 13 lug 2020, 17:59` e `Numero chiavi fonite=7`.

**Comment by lmasellis** [comment]
Android con Google Play Services 20.24.14:

![Screenshot_20200714-191412~2](https://user-images.githubusercontent.com/65446168/87455905-7435ae80-c606-11ea-912e-24783e154b95.png)

**Comment by lmasellis** [comment]
Discussione correlata per la app tedesca:
https://github.com/corona-warn-app/cwa-app-android/issues/744

Stesso problema anche lì, pare legato a Google Play Services, da capire se è solo visualizzazione oppure proprio non processa le chiavi. [polemica on] Ma non si era detto che la scelta di appoggiarsi alle API Google/Apple era garanzia di affidabilità? [polemica off].

Da notare anche che chi lì visualizza i numeri corretti vede qualcosa come 495 chiavi in un singolo aggiornamento (e sarei curioso di vedere con che frequenza), contro le nostre 7/8 chiavi ogni 3/4 giorni...

**Comment by djechelon** [comment]
Confermo zero-hash su device di mio familiare su cui è installata Immuni da giugno (Nokia 7.1 Android 10, play framework aggiornato come tutte le altre app).

@lmasellis commento
>questo costituirebbe un problema in termini di anonimato. Il protocollo Google/Apple assume che le chiavi servite in ogni file si riferiscano ad una molteplicità di utenti, e che basti mescolarle (come raccomanda la specifica) per evitare che più chiavi possano essere associate ad un utente.

Classico problema del `k`-anonimato quando `k` è pari a 1, o meno pessimisticamente "molto basso".

**Comment by lmasellis** [comment]
Nuovo file pubblicato dal backend (sequenziale 24, 7 chiavi, start timestamp Mon Jul 13 17:00:04 CEST 2020); ma Google Play Services riporta di nuovo Numero di chiavi = 0.

![Screenshot_20200716-081443~2](https://user-images.githubusercontent.com/65446168/87634045-d1338080-c73c-11ea-8c76-4a399cf8eecd.png)

> Classico problema del `k`-anonimato quando `k` è pari a 1, o meno pessimisticamente "molto basso".

Basterebbe popolare il file con alcune chiavi fittizie casuali per risolvere il problema.

**Comment by lmasellis** [comment]
Qualche statistica con confronto ad altre app europee:
https://down.dsg.cs.tcd.ie/tact/tek-counts/

Effettivamente pare che i backend di altre app aggiungano chiavi fittizie per ridurre il rischio di de-anonimizzazione nel caso di chiavi reali molto scarse. Sono confermati i numeri (scarsi) di chiavi servite, che contrastano con i report a zero di Google Play Services.

**Comment by djechelon** [comment]
Buongiorno,

al 21 luglio ancora zero chiavi in download

https://pastebin.com/mkeGyV2i

**Comment by djechelon** [comment]
Il problema si è auto-risolto. Adesso stanno scendendo giù chiavi da un paio di giorni a questa parte.

Non ne conosco il motivo.

Chiudo il ticket per quel che mi riguarda, ma abbiamo visto che non sono stato l'unico ci potrebbero essere altri col medesimo problema
