### ISSUE TITLE
Feature request: export/import data to let users change smartphone

### ISSUE THREAD

**Issue by tmontanaro** [immuni-app/immuni-documentation#136]
Feature request: I would like to export/import data (old met IDs) to let users change smartphone or format their smartphones and do not lose traces.

Obviously data should be crypted so that no one could share them outside the app and secured to do not allow to use the same data on more than one smartphone.

**Comment by thatwasso** [comment]
Workaround: use the app on both devices for 14 days, after 14 days there is no need to keep your old device, as important tracing is on your main device

**Comment by tmontanaro** [comment]
Ok but the workaround cannot be applied if you have to do a factory reset of the same smartphone 😁😅

**Comment by thatwasso** [comment]
Ho visto solo ora Torino sul profilo quindi mi sono sforzato con l'inglese senza motivo.
Comunque ho ri-flashato le gapps e ho visto che si può importare/esportare i dati direttamente dalle impostazioni google, sezione contact tracing.
![Screenshot](https://i.imgur.com/t50QcgH.jpg)

Edit: Translation for English users
I re-flashed gapps and noticed export feature directly from google settings > contact tracing.

**Comment by tmontanaro** [comment]
ENG
Wooow ... what a good news!?!
For english speakers: it is possible to import/export history through the OS Service itself! Open "Settings" -> "Google" -> "COVID19 exposure notifications" -> "exposure checks" -> verify your identity -> click on 3 dots in the top right corner -> Export/import

Now I hope developers will simply add a FAQ to explain how to do it!

ITA
Uhhhhh .... questa è una figata!
Scusa ma su github ho l'abitudine di scrivere in inglese :D 
A questo punto immagino che potranno anche mettere una FAQ con la spiegazione sul come fare!

**Comment by internall** [comment]
Issue #279 in "immuni-app-android" repository.

**Comment by tmontanaro** [comment]
Misa che ci siamo illusi ... import non c'è come opzione ... si possono solo esportare!

ENG
Perhaps we missed the fact that the "import" button does not exist ...

**Comment by internall** [comment]
Dovrebbero metterlo allora, potrebbe interessare. Se ho tempo ci do' un'occhiata da vicino.

ENG:
They should add it, it could be interesting. I'm probably going to check the code to see what I can do
