### ISSUE TITLE
Controlli esposizione: 0 controlli negli ultimi 14 giorni

### ISSUE THREAD

**Issue by beppe-boni** [immuni-app/immuni-documentation#138]
Sul mio smartphone viene riportato il seguente report sul funzionamento dell'app Immuni:
- 0 controlli negli ultimi 14 giorni
- Ultimo controllo della potenziale esposizione: 20 luglio alle ore 09:28
Il modello è: Huawei P Smart Z.

Su altri 2 cellulari di famiglia invece la situazione è differente:
- su uno, ultimo controllo: ieri sera
- sull'altro, ultimo controllo: 10 agosto
Poiché tutti teniamo attiva Immuni (con GPS e bluetooth attivi), credo che l'aggiornamento al 20 luglio e al 10 agosto possano essere una anomalia. Ho visto una issue #128 con sintomi analoghi, ma è stata chiusa.

Da verificare, grazie.

**Comment by zabi94** [comment]
Confermo, stessa situazione

Oneplus 6
OxygenOS 10.3.5 (Android 10)
Profilo di Lavoro abilitato

Forse gli endpoint non sono raggiungibili? Se mi dite dove fare il ping posso confermare la cosa.

**Comment by caeppa** [comment]
Buongiorno,

sono un utente di Immuni, ma il problema che segnalo in realtà sembra essere Android-related.
Come gli utenti del thread, anch'io vedo dal 28 luglio scorso sulla schermata delle Impostazioni/Notifiche di esposizione il campo "Controlli esposizione: 0 controlli effettuati negli ultimi 14 giorni", ma come informazione ulteriore volevo segnalare che il campo è grigliato e non permette di visualizzare la finestra di dettaglio successiva.
Grazie per qualsiasi indicazione.

Xiaomi Mi Mix 2
MIUI Global 11.0.6 Stabile
Android 9 PKQ1.190118.001

![IMG_20200912_085702](https://user-images.githubusercontent.com/71167953/92989689-4a014f80-f4d6-11ea-8aa8-c07a95ccee61.jpg)

**Comment by zabi94** [comment]
Confermo che é cosi anche nel mio caso

**Comment by raimondoDiSangro** [comment]
Ne parla anche [La Repubblica](https://www.repubblica.it/cronaca/2020/09/13/news/bug_di_immuni_mette_a_rischio_il_controllo_dei_contagi-267163423/?ref=RHPPTP-BH-I267065703-C12-P1-S2.4-T1), dovrebbe essere in arrivo un aggiornamento

**Comment by FrancescoBonizzi** [comment]
A me (Android 10) è arrivato un aggiornamento poche ore fa, una volta installato tutti i controlli esposizione sono stati valutati in un colpo e la lista è di nuovo popolata!

**Comment by zabi94** [comment]
Invece nel mio caso è stata segnata come incompatibile nello store. Annamo bene.

Non la capisco sta cosa sinceramente. Piuttosto che bloccare completamente l'app perche il battery saving la uccide, fate in modo che si possa avviare il controllo manualmente, no? Oppure lo faccia quando apro l'attività principale

**Comment by fabiobettani** [comment]
Stessa situazione anch'io, su Oneplus 6 con Android 10 e app Immuni aggiornata all'ultima versione disponibile (1.5.0). Come fare?

**Comment by fabiobettani** [comment]
Anche il nuovo aggiornamento software a OxygenOS 10.3.6, ricevuto oggi (12 ottobre 2020), non ha risolto.

Ho "risolto" manualmente così:
- ho scaricato l'app di contact tracing UK, impostandola come predefinita (va bene qualsiasi altra app nazionale di contact tracing; installarla e renderla predefinita è essenziale affinché, al passaggio successivo, Android non elimini i dati dei contatti degli ultimi 14 giorni)
- ho eliminato Immuni
- ho riavviato
- ho installato Immuni e l'ho impostata predefinita

Già al primo passaggio, l'app UK ha effettuato nuovi controlli di esposizione (come se il problema fosse di Immuni e non di Android). Dopo l'ultimo passaggio, ho verificato che finalmente anche Immuni ha effettuato nuovi controlli.

Questo non garantisce che da oggi in poi i controlli tornino a essere regolari, ma perlomeno c'è un workaround che permette di forzare il controllo senza perdere i dati di esposizione.

**Comment by beppe-boni** [comment]
Il workaround è avviare manualmente immuni ogni giorno. Il problema penso
sia che l'applicazione immuni, o meglio il suo processo in background,
viene killato da android forse perché considerato ad alto consumo della
batteria.


Il lun 12 ott 2020, 18:35 fabiobettani <notifications@github.com> ha
scritto:

**Comment by zabi94** [comment]
No, nemmeno riavviando l'app si risolve. I controlli in background continuavano a non essere fatti.
Il problema si è risolto per me con l'aggiornento dell'app di qualche settimana fa.

**Comment by fabiobettani** [comment]
Confermo, neanche nel mio caso era sufficiente aprire Immuni (e non lo è tuttora: anche dopo aver riaperto l'app, non vedo nuovi controlli di esposizione.)

**Comment by caeppa** [comment]
> Buongiorno,
> 
> sono un utente di Immuni, ma il problema che segnalo in realtà sembra essere Android-related.
> Come gli utenti del thread, anch'io vedo dal 28 luglio scorso sulla schermata delle Impostazioni/Notifiche di esposizione il campo "Controlli esposizione: 0 controlli effettuati negli ultimi 14 giorni", ma come informazione ulteriore volevo segnalare che il campo è grigliato e non permette di visualizzare la finestra di dettaglio successiva.
> Grazie per qualsiasi indicazione.
> 
> Xiaomi Mi Mix 2
> MIUI Global 11.0.6 Stabile
> Android 9 PKQ1.190118.001
> 
> ![IMG_20200912_085702](https://user-images.githubusercontent.com/71167953/92989689-4a014f80-f4d6-11ea-8aa8-c07a95ccee61.jpg)

Dopo aver aggiornato a MIUI Global 12.0.1 Stabile e disinstallato e reinstallato Immuni, una volta aperta l'app i controlli esposizione compaiono.
Sembra necessario aprire l'applicazione Immuni per far sì che i controlli avvengano (non avvengono in background): infatti, verificando con Impostazioni -> Google -> Notifiche di esposizione al COVID-19 -> Controlli esposizione, nell'elenco sono presenti vari controlli raggruppati per data e ora di avvio dell'app Immuni.

Spero che questa esperienza possa essere utile.

Cordiali saluti.
