### ISSUE TITLE
[Question] Is the app getting rid of google-apple? (ITA-ENG)

### ISSUE THREAD

**Issue by thatwasso** [immuni-app/immuni-documentation#140]
ITA: E' in cantiere la "liberazione" di immuni da google e apple? Personalmente ho tolto le gapps per riprendermi la privacy, ma vorrei anche fare la mia parte col contact tracing. Sarebbe solamente un bene non dipendere dai servizi google, magari caricando pure immuni su F-droid.

ENG: Somebody already thought about "releasing" immuni from google and apple? Personally i got rid of gapps for privacy concerns, but i also want to do my part with contact tracing. It will be only a good thing to stop depending on google play services, maybe also uploading immuni on F-droid.

**Comment by resoli** [comment]
ITA: Se può interessare, il progetto microG ha da pochissimo implementato GAEN in sw libero. La release v0.2.12.203315 include il supporto ad Exposure Notification, sviluppato da @mar-v-in . Per lo storico: https://github.com/microg/android_packages_apps_GmsCore/issues/1057 . Per l'occasione è stata anche crata una label "ExposureNotification": https://github.com/microg/android_packages_apps_GmsCore/labels/%F0%9F%A6%A0%20Exposure%20Notifications

ENG: If you are interested, the microG project has recently implemented GAEN in free/libre sw. Release v0.2.12.203315 includes support for Exposure Notification, developed by @mar-v-in . History: https://github.com/microg/android_packages_apps_GmsCore/issues/1057 . An "ExposureNotification" label has also been created: https://github.com/microg/android_packages_apps_GmsCore/labels/%F0%9F%A6%A0%20Exposure%20Notifications

**Comment by resoli** [comment]
ITA: Notare inoltre che l'implementazione potrebbe anche prescindere sia da PlayServices, che da microG (un'installazione standard di microG richiede [signature spoofing](https://blogs.fsfe.org/larma/2016/microg-signature-spoofing-security/) per poter funzionare) https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-687127954

ENG:  Also note that the implementation may in future also be independent both from PlayServices and microG (a standard microG installation requires [signature spoofing](https://blogs.fsfe.org/larma/2016/microg-signature-spoofing-security/) to work) https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-687127954.

**Comment by spinoza-dat** [comment]
ITA: Data l'implementazione di exposure notification su microG, suggerisco di cambiare il titolo dell'issue in "F-Droid Repo" per maggiore chiarezza, visto che mi sembra sia l'unico problema che rimane.

ENG: Since the implementation of exposure notification on microG, I suggest to change the issue to "F-Droid Repo" for better clearance, as it looks like it's the only problem left about it.

**Comment by alrt84** [comment]
> ITA: Se può interessare, il progetto microG ha da pochissimo implementato GAEN in sw libero. La release v0.2.12.203315 include il supporto ad Exposure Notification, sviluppato da @mar-v-in . Per lo storico: [microg/android_packages_apps_GmsCore#1057](https://github.com/microg/android_packages_apps_GmsCore/issues/1057) . Per l'occasione è stata anche crata una label "ExposureNotification": https://github.com/microg/android_packages_apps_GmsCore/labels/%F0%9F%A6%A0%20Exposure%20Notifications
> 
> ENG: If you are interested, the microG project has recently implemented GAEN in free/libre sw. Release v0.2.12.203315 includes support for Exposure Notification, developed by @mar-v-in . History: [microg/android_packages_apps_GmsCore#1057](https://github.com/microg/android_packages_apps_GmsCore/issues/1057) . An "ExposureNotification" label has also been created: https://github.com/microg/android_packages_apps_GmsCore/labels/%F0%9F%A6%A0%20Exposure%20Notifications

Ma quindi installando microG immuni funziona o solo potenzialmente potrebbe funzionare?

**Comment by resoli** [comment]
> Ma quindi installando microG immuni funziona o solo potenzialmente potrebbe funzionare?

Io la sto usando, e non ho ancora trovato alcun indizio di malfunzionamenti. MicroG permette inoltre di conoscere alcuni dettagli in più rispetto all'implementazione Google: Id correntemente trasmesso (permette di verificare da un altro telefono la corretta trasmissione e la sua potenza tramite app GAEN Detector), numero di id raccolti nell'ultima ora, istogramma con numero di id raccolti nei precedenti 14 giorni.

**Comment by alrt84** [comment]
> Io la sto usando, e non ho ancora trovato alcun indizio di malfunzionamenti. MicroG permette inoltre di conoscere alcuni dettagli in più rispetto all'implementazione Google: Id correntemente trasmesso (permette di verificare la corretta trasmissione e la sua potenza tramite app GAEN Detector), numero di id raccolti nell'ultima ora, istogramma con numero di id raccolti nei precedenti 14 giorni.

Cavolo, grazie!
Ho appena provato ad installare MicroG con f-droid, ma non riesco ad accedere all'account google con microG (credo sia necessario prima di poter usare immuni)... riproverò.

**Comment by resoli** [comment]
> Cavolo, grazie!
> Ho appena provato ad installare MicroG con f-droid, ma non riesco ad accedere all'account google con microG (credo sia necessario prima di poter usare immuni)... riproverò.

microG è un'implementazione alternativa dei Google Play Services, e quindi è di interesse primariamente per chi vuole un telefono "Google free". Immuni non richiede in alcun modo di disporre di un account Google, che è invece richiesto dai Google Play Services in cui è inserita la funzione di "Exposure Notification" su cui si basa Immuni. microG Richiede inoltre un sistema operativo sottostante capace di ["signature spoofing"](https://blogs.fsfe.org/larma/2016/microg-signature-spoofing-security/).

**Comment by resoli** [comment]
Ovviamente, nessuno garantisce che l'implementazione dell'"Exposure Notification" di microG sia corretta e funzionante in tutti i casi, quindi chi la usa lo fa a suo rischio.

**Comment by alrt84** [comment]
> > Cavolo, grazie!
> > Ho appena provato ad installare MicroG con f-droid, ma non riesco ad accedere all'account google con microG (credo sia necessario prima di poter usare immuni)... riproverò.
> 
> microG è un'implementazione alternativa dei Google Play Services, e quindi è di interesse primariamente per chi vuole un telefono "Google free". Immuni non richiede in alcun modo di disporre di un account Google, che è invece richiesto dai Google Play Services in cui è inserita la funzione di "Exposure Notification" su cui si basa Immuni. microG Richiede inoltre un sistema operativo sottostante capace di ["signature spoofing"](https://blogs.fsfe.org/larma/2016/microg-signature-spoofing-security/).

Giusto per chiarezza, quindi per utilizzare a pieno microG serve un account google e un sistema capace di "signature spoofing" (non i Huawei di ultima generazione senza i Google Play Services). Immuni funziona con microG, ma quindi servono account google e  "signature spoofing". E' una affermazione (per capire se ho capito), ma anche una richiesta di conferma. 

Infatti io sono nella condizione di aver installato correttamente microG su un sistema senza signature spooging. 
Nella schermata "Exposure Notifications" di microG è scritto "To enable Exposure Notifications, open any app supporting it", ma quando cerco di abilitare immuni mi mostra la schermata "Google Play Services non è ancora pronto. Google Play Services è aggiornato ma non può ancora abilitare le notifiche di posizione. Riprova più tardi".

Ciao e grazie

**Comment by resoli** [comment]
> > microG è un'implementazione alternativa dei Google Play Services, e quindi è di interesse primariamente per chi vuole un telefono "Google free". Immuni non richiede in alcun modo di disporre di un account Google, che è invece richiesto dai Google Play Services in cui è inserita la funzione di "Exposure Notification" su cui si basa Immuni. microG Richiede inoltre un sistema operativo sottostante capace di ["signature spoofing"](https://blogs.fsfe.org/larma/2016/microg-signature-spoofing-security/).
> 
> Giusto per chiarezza, quindi per utilizzare a pieno microG serve un account google 

**non** serve account Google per usare microG (è principalmente nato per quello)

> e un sistema capace di "signature spoofing" (non i Huawei di ultima generazione senza i Google Play Services). 

Huawei è un marca, non un sistema operativo ...

> Immuni funziona con microG, ma quindi servono account google e "signature spoofing". E' una affermazione (per capire se ho capito), ma anche una richiesta di conferma.

Ripeto, **non serve account google**, il signature spoofing è essenziale per interagire con l'infrastruttura di google (ad esempio quella per le notifiche push). Ciò non toglie che l'uso della infrastruttura di G. sia una scelta implementativa, per molti scontata, ma non per tutti. Ci sono applicazioni che ne prescindono, anche per le notifiche. 

> Infatti io sono nella condizione di aver installato correttamente microG su un sistema senza signature spooging.
> Nella schermata "Exposure Notifications" di microG è scritto "To enable Exposure Notifications, open any app supporting it", ma quando cerco di abilitare immuni mi mostra la schermata "Google Play Services non è ancora pronto. Google Play Services è aggiornato ma non può ancora abilitare le notifiche di posizione. Riprova più tardi".

microG ha una funzione di controllo della corretta funzionalità. Conviene usarla. Ad ogni modo senza signature spoofing microG non funziona, mi dispiace.

rob

**Comment by thatwasso** [comment]
@alrt84 Non serve un account google per MicroG, ma il signature spoofing è necessario. Se la tua rom non lo ha integrato, si può flashare (o pushare adb, mai fatto non ne sono sicuro).
Praticamente vai a _"far credere"_ a immuni che hai i servizi google, tramite microG che _"si spaccia"_ per GMS.

**Comment by ghost** [comment]
Io ho signature spoofing attivo e funzionante, ma non riesco comunque ad usare Immuni. Serve Phonesky (fake store)?

**Comment by resoli** [comment]
> Io ho signature spoofing attivo e funzionante, ma non riesco comunque ad usare Immuni. 

Sintomi?

> Serve Phonesky (fake store)?

Non credo, io ho il fork microg di LineageOS, e Immuni funziona senza fakestore installato. Ho abilitato in microg la registrazione dispositivo e la messagisica cloud (GCM) per avere le notifiche push, e 1 provider di geolocalizzazione (Mozilla) configurato ma non attivo..

**Comment by resoli** [comment]
Nota: il modo piú semplice per avere un cellulare con microg, facendo un favore a sè stessi e al pianeta, è prendere un cellulare ricondizionato qui:

https://e.foundation/products/?lang=it

**Comment by ghost** [comment]
@resoli 
> Sintomi?

Come succede sopra ad un altro utente, che però non ha Signature Spoofing attivo, nella schermata "Exposure Notifications" di microG è scritto "To enable Exposure Notifications, open any app supporting it", ma quando cerco di abilitare immuni mi mostra la schermata "Google Play Services non è ancora pronto. Google Play Services è aggiornato ma non può ancora abilitare le notifiche di posizione. Riprova più tardi". Ho posizione e bluetooth accesi. Dovrei anche aver creato un issue da qualche parte a riguardo, ma non ho ricevuto risposte

**Comment by thatwasso** [comment]
> 
> 
> Nota: il modo piú semplice per avere un cellulare con microg, facendo un favore a sè stessi e al pianeta, è prendere un cellulare ricondizionato qui:
> 
> https://e.foundation/products/?lang=it

Piccolo OT: a me sembra una semplice mossa di marketing solamente per lucrare sul deGoogling. A sto punto ti flashi LOs o AeX senza le gapps e sei apposto.

**Comment by thatwasso** [comment]
Comunque credo di poter chiudere il thread.

La soluzione è utilizzare **microG** o necessariamente le **gApps**, non credo venga mai cambiato il funzionamento basato su apple-google.

**Comment by resoli** [comment]
> > Nota: il modo piú semplice per avere un cellulare con microg, facendo un favore a sè stessi e al pianeta, è prendere un cellulare ricondizionato qui:
> > https://e.foundation/products/?lang=it
> 
> Piccolo OT: a me sembra una semplice mossa di marketing solamente per lucrare sul deGoogling.

Certo, e speriamo che sia sempre piú remunerativo!

> A sto punto ti flashi LOs o AeX senza le gapps e sei apposto.

E questo lo sa fare chiunque no?

**Comment by thatwasso** [comment]
> E questo lo sa fare chiunque no?

Penso che se sai che esistono alternative open source a google (e altre multinazionali), sai anche che esistono altre rom e sai come flasharle. C'è anche il fattore della determinazione a cambiare abitudini digitali, credo che chi non mastica di modding non ce la fa a cambiare radicalmente le abitudini in tal senso.
