### ISSUE TITLE
Statistics numbers of notification sent by app

### ISSUE THREAD

**Issue by filippogasbarro** [immuni-app/immuni-documentation#141]
Good morning, like written in the article on the Il sole 24 ore
[https://www.ilsole24ore.com/art/immuni-e-efficace-ultimi-numeri-luci-e-ombre-app-il-covid-19-ADESe1n](https://www.ilsole24ore.com/art/immuni-e-efficace-ultimi-numeri-luci-e-ombre-app-il-covid-19-ADESe1n)
is not clear if the total 1878 notifications sent to user that use Immuni, are the number of the people who have reported the receipt of the notification to their doctor and/or including also the people who received the notification and have not reported their positivity to the doctor. Can we know that?

Can we know both statistics numbers at today?

**Comment by ilovelinux** [comment]
> The figures for number of keys , or provided key count , indicate keys from app users who have newly tested positive for coronavirus (COVID-19). The number of matches or matched key count indicates how many of those app user keys you have been in close contact with.

https://faq.covid19.nhs.uk/article/KA-01297

**Comment by filippogasbarro** [comment]
Im'looking for the statistics of immuni. I would like to know if the statistics of the website citated are the total notification sent to immuni, or if are the notification received and reported to their ASL?

It could be interesting to know both number
