### ISSUE TITLE
Ambiguous notification information

### ISSUE THREAD

**Issue by AnderTave** [immuni-app/immuni-documentation#143]
Is it possible that someone (iOS) receives a notification referred to a specific day, but checking on the log it seems that the day with  "Numero chiavi corrispondenti" (Matched Key Count) is a 12 day after the day mentioned by Immuni app.

How is possible this difference? and which need to be considered the day of the contact, are there any interpretation of the message of Immuni (such as the day indicate something different?

**Comment by jahtjs** [comment]
Hi.
Today I’ve also received the notification referred to a specific day (the tenth of October), but checking the log I’ve two “numero chiavi corrispondenti” only seven days after (the seventeenth of October).
I’ve asked the reason to the Immuni’s support by mail and they answer me that I’ve met those two persons on the tenth of October but they have  been tested positive for the swab only seven days after and so they have updated their situation on the app only on seventeenth of October.
:(

**Comment by ilovelinux** [comment]
You exchange the key on day X, which is the day you have been in contact with the infected person. The apps saves the key and the day of exchange.
After a several days that person results positive and their key is registered on Immuni servers. Your device, which periodically looks at the new positive keys, notice that you met with that person. It sends you a notification where it says that you met them the day X. Obviously the key matches only the day you get the notification.

**Comment by AnderTave** [comment]
@ilovelinux that is kind of obvious, in my case this is the situation of a friend:

"receive" on day Z a notification on Immuni saying that on day Y she had a positive contact since was a day she spent totally at home she was curious, I told her to check the "Numero chiavi corrispondenti" (Matched Key Count) and it was written that she had the matched key on day X.

As far as I can understand, is ok that there is a day Z which is different by the day Y, but is not clear why there is a different between a day Y (the one in Immuni) with a day X (the one on iphone system, or I assume also android has some similar setting)
