### ISSUE TITLE
[Feedback] The app lacks of a Dark mode

### ISSUE THREAD

**Issue by thatwasso** [immuni-app/immuni-documentation#144]
I think the app misses a dark mode. Nowadays every app has a dark mode and seeing all this white is really frustrating for the eyes, It's like a flashbang in real life.
Plus another great addiction should be black mode for OLED displays, for battery savings.

**Comment by internall** [comment]
I totally agree.

**Comment by qub1750ul** [comment]
Duplicate of #100

**Comment by thatwasso** [comment]
> 
> 
> Duplicate of #100

Closed.
