### ISSUE TITLE
Perchè non c'è una versione per Ipad?

### ISSUE THREAD

**Issue by garethjax** [immuni-app/immuni-documentation#145]
Salve,
un mio amico che ha un cellulare molto obsoleto (ma con cui si trova bene) non può installare immuni.

Però ha un ipad che si porta costantemente dietro quando è in giro, ed è un modello comprato questa estate, quindi sicuramente aggiornato all'ultimo sistema operativo.

Come mai non è possibile avere una versione per ipad? O in generale per tablet moderni android?

**Comment by multiformeingegno** [comment]
Perché gli iPad non supportano le Exposure Notification APIs. Decisione di Apple.

**Comment by garethjax** [comment]
Che peccato! 

Grazie comunque!
