### ISSUE TITLE
[GENERALE] Non posso installare su device Huawei 2020

### ISSUE THREAD

**Issue by cascafico** [immuni-app/immuni-documentation#146]
Leggo nelle FAQ:
> "A causa di limiti tecnici, questa tecnologia non è disponibile su versioni precedenti di iOS, Android e Google Play Services"

Il mio telefono è un Huawei Y5p del 2020, dotato di versione Android 10. Non possiede una precedente, nè attuale versione di Google Play Services. Google Play Services non è installabile e, senza questo servizio, nemmeno Immuni; inoltre Google Play Services mi viene richiesto anche se tento l'installazione con pacchetti apk.

Ci sono lunghissime liste di app che possono essere installate senza Google Play Services; c'è una motivazione tecnica per la quale non è possibile compilare Immuni indipendentemente?

Devo dedurre che Immuni non è disponibile in quanto Google è costretto ad aderire a blocchi sanzionatori verso la Cina?

**Comment by Nikolay992** [comment]
La motivazione principale per la quale non è disponibile è che l'app utilizza un sistema di notifica sviluppato da Apple e Google. La prerogativa lato Android è ovviamente l'utilizzo dei Google Play Services. Di seguito il link al sistema di notifiche di cui parlo poco sopra.

https://www.google.com/covid19/exposurenotifications/

**Comment by cascafico** [comment]
> La motivazione principale per la quale non è disponibile è che l'app utilizza un sistema di notifica sviluppato da Apple e Google.

Riformulo la mia domanda: non esistono al mondo altri servizi di notifica oltre a  Google ed Apple?

Pensavo che tra i requisiti del progetto, quello del raggiungere la massima diffusione della app fosse fondamentale.

**Comment by Nikolay992** [comment]
La massima diffusione dell'app è fondamentale, nell'ottica nella quale sia applicabile tecnologicamente. Huawei con i suoi dispositivi senza servizi Google impediscono l'implementazione(facile, veloce e sicura) del sistema di tracciamento di Immuni.
Il numero di dispositivi che non utilizzano servizi Google è veramente basso(esclusi i device con iOS).

**Comment by cascafico** [comment]
> Huawei con i suoi dispositivi senza servizi Google impediscono l'implementazione(facile, veloce e sicura) del sistema di tracciamento di Immuni.

Non è chiaro chi sia il soggetto nella frase sopra: Huawei impedisce? I servizi Google impediscono? 

A leggere quanto [dichiarato da Google](https://support.google.com/android/thread/29434011?hl=en) ("This government action prohibits all US companies, including Google, from collaborating with Huawei."), è l'amministrazione USA a vietare a Google l'implementazione di Google Services per Huawei, mentre dalla vostra frase, sembra sia Hawei a rigettare Google Services ed impedirne l'implementazione.

> Il numero di dispositivi che non utilizzano servizi Google è veramente basso(esclusi i device con iOS).

Siamo sui 900.000 nel primo quadrimenstre 2020. Per cortesia, vogliate chiarire se l'azienda sviluppatrice di Immuni non è in grado oppure non intende rendere compatibile la app. Se, insomma, posso aspettarmi in futuro degli aggiornamenti di compatibilità per i dispositivi Hawei.

**Comment by Nikolay992** [comment]
L'azienda sviluppatrice non è più l'azienda che ne detiene la manutenzione e gli sviluppi futuri. D'ora in poi Sogei e PagoPA se ne occuperanno e no, non è stata in grado di rendere compatibile la app con dei dispositivi non compatibili.

È l'amministrazione USA a vietare questa implementazione, l'unica possibilità di ricevere aggiornamenti di compatibilità potrebbe esserci nel caso l'amministrazione USA cambiasse presidente e nel caso decidesse di revocare le varie restrizioni a Google nei confronti di Huawei.

**Comment by ilovelinux** [comment]
Related to https://github.com/immuni-app/immuni-app-android/issues/260
