### ISSUE TITLE
Compliance with Italian Government guidelines on security for pubblic software

### ISSUE THREAD

**Issue by cheTesta** [immuni-app/immuni-documentation#15]
Please remember to submit informations on compliance with AGID guidelines on secure software

https://www.agid.gov.it/it/sicurezza/cert-pa/linee-guida-sviluppo-del-software-sicuro

**Comment by SannitaSSJ** [comment]
Duplicate of #7

**Comment by gvdr** [comment]
It's not a duplicate. #7 is just asking about opening the source code. The Agid guidelines requires also additional information.

**Comment by immuniopensource** [comment]
Hi @cheTesta and thanks for your contribution. We are aware of the documents that you linked us and we confirm we follow, as much as possible, those AgID guidelines in our software development lifecycle. Please remember that those documents are guidelines, a set of best practices, and not policies to set a compliance score. Let us know if you need further info, I am closing this issue for now. Thanks!
