### ISSUE TITLE
keyCount value

### ISSUE THREAD

**Issue by agiancas** [immuni-app/immuni-documentation#150]
![Cattura](https://user-images.githubusercontent.com/73528733/97322175-d04bd800-186f-11eb-90fd-90ac6a2f6633.JPG)

Da qualche giorno nel log dei controlli del mio Immuni, si presenta quasi sempre un doppio controllo alla stessa ora, il primo con un numero di chiavi "compatibili" con come mi sono spostato e raccolto contatti in giro, il secondo controllo con un numero abnorme di chiavi (ad esempio 3545 o 3996, come nella foto allegata), o addirittura in alcuni casi anche di oltre 9000 chiavi.

Prima del 20 ottobre, ciò non accadeva, non ho fatto cancellazioni o re-installazioni al mio Immuni. Uso un adroid Huawei p10, emui 9.1

**Comment by Trainax** [comment]
Buonasera.

**Questa risposta si basa sulla mia analisi del codice e potrebbe non essere totalmente esatta.**

Il valore keyCount si riferisce al numero di chiavi che sono state scaricate dal server centrale perché sono state caricate da utenti positivi. Il tuo cellulare scarica tutte le nuove chiavi che sono state caricate dall'ultimo controllo a quando il tuo telefono avvia il download, poi in locale viene verificato se esiste una o più corrispondenza/e (matchesCount) con le persone che hai incontrato nei tuoi spostamenti (le cui chiavi sono salvate in locale sul tuo dispositivo).
Quei numeri sono normali. Io restando sempre in casa per 2 settimane (periodo di conservazione dei controlli esposizione) ho avuto numeri simili sebbene non abbia incontrato nessuno a parte mia mamma e mio papà
