### ISSUE TITLE
number of matching keys

### ISSUE THREAD

**Issue by macslacky** [immuni-app/immuni-documentation#151]
Hello
I have an iphone, if I go to the exposure log I find
"corresponding keys number 0"
what does that zero mean?

**Comment by Trainax** [comment]
The number 0 means that there were no matches between the keys which were saved on your device (exchanged with people you have met) and the keys (uploaded by positive users) which were downloaded from the central server when the check was done

**Comment by Trainax** [comment]
Dear @macslacky, did you find my answer satisfactory? Or is there something else you would like an answer for?

More than a month has passed without a reply from your side. If your question has been answered, I think it would be appropriate for you to close this issue 😉.

Best regards

**Comment by macslacky** [comment]
perfect, thank you for the clarification
sorry if i forgot to close it
