### ISSUE TITLE
incorrect exposure control

### ISSUE THREAD

**Issue by macslacky** [immuni-app/immuni-documentation#152]
hi, I checked today's 12/30/20 exhibits and I see two exhibits at 08.06 and 12.08
i was working from home, i live alone so it was impossible to meet other people
except it hooked up to a neighbor's device
I have an iphone X with an iwatch 5 with active virtual sim

![IMG_2193](https://user-images.githubusercontent.com/34606573/103357883-8e7c1f80-4ab4-11eb-83ea-b6e7be281f04.jpeg)

**Comment by Trainax** [comment]
Those are all the times your phone has established a connection with the central server to download the keys uploaded by positive users.

The phone then checks locally if there are any matching keys between the keys downloaded from the server and the keys locally saved on your device exchanged with people you have met (this check is considered one *Controllo esposizione* by your device).

There is no correlation between the time a check happens and the fact if you are alone or not

**Comment by macslacky** [comment]
perfect, thank you for the clarification
sorry if i forgot to close it
