### ISSUE TITLE
Which version of ENF is Immuni using?

### ISSUE THREAD

**Issue by Ein-Tim** [immuni-app/immuni-documentation#154]
I am curios which version of the Exposure Notification Framework / the Exposure Notification System Immuni is using?

Version 1 or 2?

**Comment by Ein-Tim** [comment]
I think I found the info in: https://github.com/immuni-app/immuni-app-ios/blob/618ab3853504c289671485a40b166e54f58c215a/project.yml#L90.

It's version 1.

**Comment by fsbaraglia** [comment]
yes, I posted as well here my find https://github.com/corona-warn-app/cwa-app-ios/issues/1731#issuecomment-755446247
