### ISSUE TITLE
[Feature Request] Enable AIRE residents to download green pass using passport

### ISSUE THREAD

**Issue by MarcoSignoretto** [immuni-app/immuni-documentation#158]
Enable AIRE residents to download the green pass using passport number and AUTHCODE, this feature is available through the website https://www.dgc.gov.it/spa/public/ but not from Immuni where you can only retrieve the certificate if you have an Italian health card "Tessera Sanitaria"

**Comment by mizrael** [comment]
this would be a very nice addition.

**Comment by pierotriverio** [comment]
The problem is that the "health insurance card" field only accepts numbers. A passport number cannot be entered since it contains also some letters.

**Comment by DaFlowah** [comment]
Having the same issue.
According to the instructions provided on the offical FAQ [here](https://www.dgc.gov.it/web/faq.html#pvaccinatestero), we can do it from web by selecting “Utente senza tessera sanitaria o vaccinato all’estero”, option that is not available in the app.
I emailed cittadini@immuni.italia.it nine days ago for this issue, but they haven't come back to me yet.
