### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by angelogulina** [immuni-app/immuni-documentation#16]
First of all, thanks for making this available - it's a great contribution to the community.

Related to *Privacy*, I find the documentation a bit lacking. 
Few examples:
- it's good the app will give some communication to the user https://github.com/immuni-app/documentation/blob/2c3bdb611f5365e765d6b9ec131b8cb45d1d9aa0/Product%20Description.md#L61 but the community should know more about how privacy is preseved;
- same here: https://github.com/immuni-app/documentation/blob/f053e8e2f87aa70e9193f33f38ba6f011b4dd8e1/Technology%20Description.md#L130 with the additional mention of the _Analytics Service_, of which I can't find much more details either.

Are you planning to details those parts?
Are you considering adopting [TCN](https://tcn-coalition.org/) protocols and the (specification)[https://www.apple.com/covid19/contacttracing/] provided by Apple and Google.

Thanks!

**Comment by immuniopensource** [comment]
Hi @AngeloGulina, are your concerns still valid? Thanks

**Comment by angelogulina** [comment]
Hi @immuniopensource, thanks for getting back to me.

In order to give you an answer, it would be useful to know whether the concerns were addressed with addition to the documentation. Can you perhaps share some links.

Thanks!

**Comment by immuniopensource** [comment]
Yes @AngeloGulina, see for example the [Privacy Preserving Analytics](https://github.com/immuni-app/immuni-documentation/blob/master/Privacy-Preserving%20Analytics.md) documentation file. 
Thanks for your time.

**Comment by angelogulina** [comment]
Great @immuniopensource! We can close this!
