### ISSUE TITLE
[Feature Request] Allow to import the Green Pass in Apple Wallet and Google Pay

### ISSUE THREAD

**Issue by DaFlowah** [immuni-app/immuni-documentation#160]
Hi there,
it would be nice to allow users to import their Green Passes into the Apple and Google's cards apps.
I'm not very familiar with Apple, but Google already [updated its APIs](https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html).
I can see there are already unofficial tools to perform this actions [CovidPass ](https://github.com/covidpass-org/covidpass) and [Pass2Pay](https://play.google.com/store/apps/details?id=color.dev.com.tangerine&hl=it&gl=US) (that is not even open source and [shares your data](https://www.mobileworld.it/2021/08/05/aggiungere-green-pass-google-pay-286458/)). An official feature would be much appreciated.
I can see something similar has been discussed (and deprecated?) [here](https://github.com/pagopa/io-app/issues/3168) for IO.

**Comment by alessionossa** [comment]
I am not sure if this can actually be implemented in EU with DGC, but in iOS 15.1 there is the possibility to import [SMART Health Cards in Apple Wallet](https://developer.apple.com/news/?id=7h3vwlh5)

Here is some reference from WWDC2021: [Explore Verifiable Health Records - WWDC 2021](https://developer.apple.com/videos/play/wwdc2021/10089/) and from Apple Developer Documentation: https://developer.apple.com/documentation/healthkit/hkverifiableclinicalrecord

SMART Health Cards specifications: https://smarthealth.cards/

**Comment by dhinterlechner** [comment]
Any update on this? As we need the GreenPass now everywhere, I would like to see the feature to view the QR code without any internet connection. While skiing in the mountains to enter a restaurant I have to show it but not everywhere there is a good internet connection. Saving the QR code as image isn't any option as you have to search it between many many other photos unless you save a new copy of the greenpass everey day....

**Comment by DaFlowah** [comment]
The English [NHS App](https://play.google.com/store/apps/details?id=com.nhs.online.nhsonline&hl=it&gl=US) has managed to integrate the feature:

![Immagine](https://user-images.githubusercontent.com/33235583/147687960-d87fa767-898d-4d89-a186-a45395b7d040.png)

**Comment by alessionossa** [comment]
Following https://github.com/immuni-app/immuni-documentation/issues/160#issuecomment-951795806, as mentioned in https://github.com/pagopa/io-app/issues/3168#issuecomment-1025148226

> Finally, Apple implemented support for EU Digital COVID Certificate as stated in [iOS & iPadOS 15.4 Beta Release Notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15_4-release-notes#HealthKit)
> It is supported out of the box [through iOS Camera app](https://twitter.com/viticci/status/1487769115246923778), but it would be better to have a button directly in IO App to add the DCC as a Verifiable Health Records (technical references: [HKVerifiableClinicalRecord Documentation](https://developer.apple.com/documentation/healthkit/hkverifiableclinicalrecord), [euDigitalCOVIDCertificate HKVerifiableClinicalRecordSourceType](https://developer.apple.com/documentation/healthkit/hkverifiableclinicalrecordsourcetype/3922615-eudigitalcovidcertificate))
