### ISSUE TITLE
Person instead of user

### ISSUE THREAD

**Issue by macteo** [immuni-app/immuni-documentation#23]
_User_ (utente) is a very common expression to refer to the person using any app.

However I would suggest to call the word _person_ (persona) as it is more inclusive and has a strong relations with real life contacts.

Furthermore, as in the future the Immuni backend should be able to fetch positive contacts from other app backends (used in other countries), the Immuni user could be notified of contacts occurred with people that are not Immuni users themselves, but are still people.

**Comment by immuniopensource** [comment]
Dear @macteo, thanks for your input. We had this very discussion with the team. We recognize there is no perfect answer on this, but we believe "user" to work a bit better, as it is more specific. For example, it helps clarify that users will not be notified of risky exposures to non-users. Of course your arguments have merit too.
