### ISSUE TITLE
please clarify the sentence "These keys are generated randomly and change once per day"

### ISSUE THREAD

**Issue by giodegas** [immuni-app/immuni-documentation#25]
What kind of random generator is used?

Is it based on a [Cryptographically_secure_pseudorandom_number_generator](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator) ?

If not, which one? Reference?

If yes, could you provide a dataset of generated keys?

**Comment by GennAvi** [comment]
I guess they just use what the A/G API gives them...but let's wait someone from the team for clarifications

**Comment by earien** [comment]
@giodegas , you can refer to the official A/G specifications for details on the algorithm being used for generating the keys, as they are completely managed by the A/G Exposure SDK 😊
In particular, check the Cryptography Specifications here: https://www.apple.com/covid19/contacttracing

**Comment by vincenzoiovino** [comment]
> @giodegas , you can refer to the official A/G specifications for details on the algorithm being used for generating the keys, as they are completely managed by the A/G Exposure SDK 
> In particular, check the Cryptography Specifications here: https://www.apple.com/covid19/contacttracing

I gave a look at the Goople's doc you refer.
All functions are defined except for CRNG function, the doc just says that it is "A cryptographic random number generator" without specifying which one.

Thanks to Edward Snowden it is now well known that NSA attempted to put backdors in some CRNG, see here: https://en.m.wikipedia.org/wiki/Dual_EC_DRBG
So our National security Is in the good hands of private foreign companies that do not fully specify some pseudorandom functions even though previous attempts to put backdoor in them are widely known.

**Comment by xb8** [comment]
if the crypto function is not open source and well documented the app is a hard pass for everyone

**Comment by devfly9** [comment]
In the Apple document, it's mentioned the CRNG that let me think they refer to this one: https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator. 

Please, clarify if the assumption is correct.

**Comment by GennAvi** [comment]
CRNG is just a name of a cryptographic object, it does not refer to a concrete instantiation. The one mentioned by @vincenzoiovino was also believed to be a CRNG but it tuned out it wasn't.

**Comment by devfly9** [comment]
> CRNG is just a name of a cryptographic object, it does not refer to a concrete instantiation. The one mentioned by @vincenzoiovino was also believed to be a CRNG but it tuned out it wasn't.

@GennAvi CRNG is a function.

Page 4 in https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf. The CRNG is a **function** that designate a cryptographic random number generator.
![Screenshot 2020-05-17 at 12 51 10](https://user-images.githubusercontent.com/65502871/82154620-16226000-983d-11ea-862c-f68e1771d80e.png)
That *should* be this [function](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).

**Comment by ivanvisconti** [comment]
> That _should_ be this [function](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).

@devfly9  CRNG is not a function, is a name of a function, and everyone can write any function calling it CRNG. It might easily be a function that includes a backdoor.

**Comment by devfly9** [comment]
> > That _should_ be this [function](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).
> 
> @devfly9 CRNG is not a function, is a name of a function, and everyone can write any function calling it CRNG. It might easily be a function that includes a backdoor.

"function" or "name of a function" doesn't really make any difference in this context. Google and Apple are calling it "function". 
You can call a Linear Function: f(x) = mx + b, "pippo", "pluto" or "batman"...

When the code will be open-sourced you are free to see the implementation and search for any backdoor. If not implemented in the G/A SDK that might not be open. In that case Google or Apple should provide details on its implementation.

**Comment by GennAvi** [comment]
@devfly9 Thank you for having explained us what a function is (according to you).
Imagine you have to produce an ordered list...if someone asked you which algorithm you intend to use, would you answer with this wikipedia link? https://en.wikipedia.org/wiki/Sorting_algorithm

**Comment by devfly9** [comment]
@GennAvi, as I said, the implementation is not specified. And not even documented in the Apple/Google spec. They just say they are going to use the CRNG function and implementation is not specified.  We have to wait for an answer from the developers or see the code.
The doc just says that it is "A **C**ryptographic **R**andom **N**umber **G**enerator"(=CRNG) without specifying which one.
P.S.  I didn't give any function definition...

**Comment by gvdr** [comment]
I find suspicious the activity of users that just joined github this month. and whose only contribution is making confusion in this thread. @devfly9, please refrain from commenting unless you can add relevant information to the issue.

**Comment by vincenzoiovino** [comment]
> @GennAvi, as I said, the implementation is not specified. And not even documented in the Apple/Google spec. They just say they are going to use the CRNG function and implementation is not specified.

"to use A CRNG function" not "to use THE CRNG function".

> We have to wait for an answer from the developers or see the code.

In another issue in this repo (see the issue about Google play service) somebody said that the API Is going to be distributed in Google play service that has closed source (?).
So It Is likely that we will never know which functions It Is(?). Moreover there are confirmed attempts from NSA to put backdors in CRNG functions (see above reference).

How could such trapdoor be used?
I do not know but I will try to raise some "suspicions" in next days after I will have understood which permissions you grant to play services in order to be able to run Immuni via IPC (to my current knowledge to run Immuni, play service needs access, not to GPS, but to network provider data).

Notice that by raising "suspicions" I do not intend to make unnecessary controversy.
A security analysis should unveil the worst-case scenario based on the known facts.
And, as I said, due to previous attempts to put backdoors for surveillance purposes, any "suspicion" should not be underestimated.

**Comment by vincenzoiovino** [comment]
> I find suspicious the activity of users that just joined github this month. and whose only contribution is making confusion in this thread. @devfly9, please refrain from commenting unless you can add relevant information to the issue.

We should refrain from discrediting or trying to throw anybody out from the discussion. 
We are here also to learn.

**Comment by gvdr** [comment]
I stand corrected. Please let's all try to keep this to the point (there including myself).

**Comment by devfly9** [comment]
> I find suspicious the activity of users that just joined github this month. and whose only contribution is making confusion in this thread. @devfly9, please refrain from commenting unless you can add relevant information to the issue.

@gvdr This is actually irrelevant for this discussion. You just added two comments without adding nothing relevant for the discussion, and mine here is the third one. All the previous comments are related to this issue. We all know what can be relevant and what not.

**Comment by immuniopensource** [comment]
Good morning @giodegas and all, you can find more information on the key-generation algorithm and, more generally, on the implementation of the Exposure Notification framework in the [Apple Exposure Notification implementation source code](https://developer.apple.com/exposure-notification/) and in the [Google Exposure Notifications internal repository](https://github.com/google/exposure-notifications-internals). Thank you!
