### ISSUE TITLE
license and TOS are illspecified or missing

### ISSUE THREAD

**Issue by gvdr** [immuni-app/immuni-documentation#28]
In the issues and in some documents it is mentioned that the app will be under MPL (https://innovazione.gov.it/app_Immuni_risposte_quesiti_anorc/). In the README, in the context section, the license is specified as GNU AGPL 3 (https://github.com/immuni-app/documentation#context). In the AGID guide lines the license is specified as EUPL (https://www.agid.gov.it/it/agenzia/stampa-e-comunicazione/notizie/2019/05/13/pubblicate-linee-guida-agid-sullacquisizione-il-riuso-del-software-nella-pa).

At the moment, it is not possible to understand which (if any) of these licenses will be adopted.

Similarly, the context document, there's a reference to a Terms of Service and a Privacy Notice document. Both of them are missing.

**Comment by fpietrosanti** [comment]
The Agid Guidelines does not specify to use EUPL but provide a range of OSI licenses, including AGPLv3. 
Here my analysis on why AGPLv3 is the best one for Immuni including all the detailed reference to the License Choice chapter of Agid Guidelines https://forum.italia.it/t/requisiti-normativi-su-riuso-app-di-contact-tracing/14284 .

Here comment by the developer on the choice of AGPLv3:
“then switched to AGPLv3 in response to advice coming from the open-source community” https://github.com/immuni-app/documentation/issues/7?#issuecomment-629643173

Considering the timeline of the various source of information and the legal compliance of AGPLv3, i'd consider AGPLv3 the license.

Note: We may argue who's the copyright owner, it should be "2020 (c) Commissario straordinario per l'emergenza Covid-19 - Presidenza del Consiglio dei Ministri" as defined by https://github.com/immuni-app/documentation/blob/master/LICENSE.md

**Comment by immuniopensource** [comment]
Thanks for this important discussion. Right now each repository contains the LICENSE file and the relative documentation. Please refer to the [website](https://www.immuni.italia.it/) to find extended information regarding the ToS and PN files. I am closing this issue for now, thank you!
