### ISSUE TITLE
AppStatus: Don't use "Protection" word.

### ISSUE THREAD

**Issue by studiofuga** [immuni-app/immuni-documentation#29]
The use of the word "Protezione attiva/non attiva" should be avoided.
The risk is to give a false sense of security to the user.
Better use the word "Applicazione attiva" or "Tracking" or "Exposure tracking".
This is very important, because the app doesn't provide ANY protection, but only a monitoring of the exposure.

**Comment by gvdr** [comment]
Strongly agree. I wrote that somewhere else too.

A message like this risks a lot to convey complacency in the people using the app.

More in general, the wording of the app is extremely important and delicate. I know you mentioned copywriters and lawyers supervising this documentation. But I never read anything about science communicators being involved in phrasing the text, and this is crucial.

**Comment by enrichman** [comment]
Agree. Since Immuni is going to be distributed as a "contact tracing" app I would suggest "Tracing attivo" or "Tracing attivato".
The past form is more clear, since it explains in which state the app is.
