### ISSUE TITLE
Interoperability required

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-documentation#30]
I see no reference to interoperability with foreign systems using the same A&G protocol or other systems. This is essential to make the app effective upon substantial reopening of EU internal borders.

In-depth discussion here:
https://drive.google.com/file/d/1mGfE7rMKNmc51TG4ceE9PHEggN8rHOXk/edit

**Comment by eadmaster** [comment]
[here](https://thenewstack.io/why-covid-19-contact-tracing-requires-a-distributed-database/) they suggest to use a distributed db like Cassandra or MongoDB for this, but all the contact tracing apps should use the same schema this way.

**Comment by carallo** [comment]
Closed because of...?
