### ISSUE TITLE
App name is misleading

### ISSUE THREAD

**Issue by lbrutti** [immuni-app/immuni-documentation#35]
Hello,
I think app name is dangerously misleading, giving a false security feeling of immunization.

Contact tracing apps are use to track **infected** people.

**Comment by 5N44P** [comment]
What about

![image](https://user-images.githubusercontent.com/65452638/82120700-4e1b9b80-9788-11ea-8631-380ba4f08d29.png)

Just a joke, couldn't resist, sorry!

**Comment by AndreazLattmann** [comment]
@F5F0EF 😂🤣

**Comment by Polyterative** [comment]
Do we know who approved the name?

**Comment by manuelmazzuola** [comment]
IMO **immuni** is a well-thought app name, it reminds me of the herd immunity/social immunity, an _[indirect protection from infectious disease](https://en.wikipedia.org/wiki/Herd_immunity)_, just what **immuni** want to achieve. :man_shrugging:

**Comment by Hissvard** [comment]
Ehh, if I opened Immuni-app on my phone I'd be like "Oh nice I can track immune people!" which as Ibrutti said isn't what it does.

Heck, if we wanted to be pedantic do we even know how long immunity lasts?
The name sounds good and positive but I wouldn't call it correct.

**Comment by diasalvatore** [comment]
@F5F0EF +1

**Comment by Lemen47Nic** [comment]
Can I use the app to find a new girlfriend? Maybe after the pandemic is over it could be renamed and used in a different way.

Sorry 🙏🏻

**Comment by SannitaSSJ** [comment]
I think this "issue" can be closed.

**Comment by ALBUCHERQUE** [comment]
LOL https://www.reddit.com/r/ItalyInformatica/comments/gml03y/immuni_app_name_is_misleading/

**Comment by lbrutti** [comment]
Ok, this issue was a provocation.

Thanks for the partecipation
😁
