### ISSUE TITLE
Custom http headers must be scoped

### ISSUE THREAD

**Issue by ioggstream** [immuni-app/immuni-documentation#38]
## I expect

Custom HTTP headers to have a scope. See https://tools.ietf.org/html/rfc6648

## Instead

They have not: `Exp-Dummy-Data` & co should be `Immuni-Exp-Dummy-Data`

## Note

Fix it *after* merging #33 and #34 

See https://github.com/immuni-app/documentation/blob/master/API.yaml#L82

**Comment by immuniopensource** [comment]
Hi @ioggstream and thanks for your contribution. This has been fixed as you may see in the latest version of the specs: https://github.com/immuni-app/immuni-documentation/blob/master/API.yaml. Let us know if there are any more problems. Thanks!
