### ISSUE TITLE
Typo: information is a collective noun

### ISSUE THREAD

**Issue by ioggstream** [immuni-app/immuni-documentation#39]
## Nitpick

Here and everywhere: information is a collective noun, so you don't expect to use it with plural (eg. `infos`).

https://github.com/immuni-app/documentation/blob/e09ec5b327f55d0543f4235f44ffb606a0b0a52f/API.yaml#L209

## Note

Fix it *after* merging #33 and #34

**Comment by ckeenan151** [comment]
Hi Roberto,

Thanks for raising this point. I actually answered it in #26, so please excuse the C+P!

Christy

--

The _Info_ versus _Infos_ debate is one that we had internally during the drafting process.
You are absolutely correct to note that _Information_ is an uncountable noun. However, in this case, it can be helpful to think of _Info_ not as an abbreviation of _Information,_ per se, but as the name of a certain type of defined unit (_Exposure Info, Technical Info,_ etc.). There can be—indeed, there are—more than one of these units. As such, these defined units’ names would become _Exposure Infos_ and _Technical Infos_.

Please know that, as a native English speaker, _Infos_ isn’t particularly pleasing to my ears either! I recognise why you would raise this flag, and I appreciate that you have done so. However, having debated it within the company on several occasions, we are happy with our decision to retain the original in this case.

Thanks again for your input.

Christy
Lead Copywriter

**Comment by ioggstream** [comment]
Hi Christy and thanks for your reply.

As it seems that the rationale of your decision can be relevant to the project and has semantic impacts on the API fields.
If that's not already documented, I strongly suggest to  find a suitable place in the documentation: if you decide to do so you could reference this issue, otherwise just let me know and I'll close it.
