### ISSUE TITLE
Please make clear who are the team members and start handling the issues systematically

### ISSUE THREAD

**Issue by GennAvi** [immuni-app/immuni-documentation#50]
Up to now there has been a lack of moderation of the issue section which, in my opinion, generates so much confusion and noise. It is not clear who is speaking on behalf of whom and who are the team members. Probably, it is written somewhere, but you should make it more explicit. In this way,  when one reads the issues, he can easily discriminate who is a team member and who is not. Also, you should start putting labels to the issues, and clearly state what is the action you are going to take about them.
Thank you

**Comment by vincenzoiovino** [comment]
> Up to now there has been a lack of moderation of the issue section which in my opinion generates so much confusion and noise. It is not clear who is speaking on behalf of whom, who are the team members. Probably it is written somewhere, but you should make it more explicit. In this way, when one reads the issues he can easily discriminate who is a team member and who is not. Also you should start putting labels to the issues, and clearly state what is the action you are going to take about them.
> Thank you

I totally agree. Not just for Immuni's Team but also for the teams of the Ministry and every party directly and indirectly involved.
It is enough to add your signature at the end of the message. The signature may be also a pseudonym until you clearly state that you participated actively in the process in Team XXX.

Of course who is not involved in the development and decisional choices can stay anonymous.

**Comment by gvdr** [comment]
@luke10ferrari @paolo-de-rosa this is an issue you really should take the time to read.

**Comment by ivanvisconti** [comment]
Everything seems to be stuck. Are we wasting time? @luke10ferrari @paolo-de-rosa could you please tell us when the discussion will be properly managed?

**Comment by SannitaSSJ** [comment]
Maybe, _maybe_, it might be also good if people would refrain from flooding 24/7 the project with "issues" and comments to "issues".

Maybe, _maybe_, it might be good to let people do their work, and wait patiently for them to fix all the things that need to be fixed, instead of pinging them for every single whim a human brain is capable of thinking of.

Disclaimer: I _do not_ work for Bending Spoons, nor I am affiliated to BS in any way. I'm just a regular citizen who's just _a tad_ annoyed by the amount of noise on this project - that, by the way, it is **in no case** responsibility of who's managing this project, rather of the users who continue to post in here 24/7.

**Comment by gvdr** [comment]
So we should refrain from signalling what are critical issues not to disturb them? Maybe. Maybe, instead, people can do their job and answer issues as it is done in any other open source project. Maybe.

**Comment by SannitaSSJ** [comment]
@gvdr Plonk.

**Comment by drumbsd** [comment]
Ma non avete un cazzo da fare nella vita, oltre a spaccare le balle a questa gente? In altri progetti opensource vi avrebbero già dato non so quanti calci nel culo.

**Comment by gionn** [comment]
> In altri progetti opensource vi avrebbero già dato non so quanti calci nel culo.

Avrebbero già chiuso sistematicamente le issues per off-topic.

Già, questo sarebbe il repo della documentazione del progetto, non la sezione "chiedi al team", e anche io sono abbastanza annoiato dall'esser sommerso di notifiche inutili, apritevi un subreddit se volete discutere di tutto quel che vi passa per la testa.

**Comment by strzelca** [comment]
> Già, questo sarebbe il repo della documentazione del progetto, non la sezione "chiedi al team", e anche io sono abbastanza annoiato dall'esser sommerso di notifiche inutili, apritevi un subreddit se volete discutere di tutto quel che vi passa per la testa.

Io ho paura solo a pensare se qui ci fosse stato Torvalds, sono abbastanza convinto che sarebbero fioccati così tanti morti da far sbiancare anche il COVID in termini numerici.

**Comment by GennAvi** [comment]
@immuniopensource why are you still not considering all the issues systematically? For each issue, you should clearly state what is your opinion about it and if you are going to address the expressed problem or not. If you consider some inputs not in focus with your goals, then clearly express why and close the issue. This is critically important both for transparency and for having an ordered and effective issue section.
