### ISSUE TITLE
health records collection, storing and recording huffingtonpost.it)

### ISSUE THREAD

**Issue by p43b1** [immuni-app/immuni-documentation#56]
Hi,

I just read this article [https://www.huffingtonpost.it/entry/dentro-immuni_it_5ec3d79fc5b61dc1549dd87c](url) where the author states:

> Secondo quanto appreso da Huffpost, il download dovrebbe essere disponibile ai cittadini nella prima settimana di giugno e tra gli step preliminari per il suo utilizzo le stesse fonti parlano di un questionario che **l’utente dovrà compilare con i suoi dati anagrafici e i dettagli del suo stato di salute, comprese informazioni relative a eventuali familiari contagiati, tamponi effettuati o test sierologici,** così da avere un quadro completo della propria condizione come si farebbe di fronte a un medico.

From Google Translate

> According to what has been learned from Huffpost, the download should be available to citizens in the first week of June and among the preliminary steps for its use the same sources speak of a questionnaire that **the user will have to fill in with his personal data and details of his status health, including information relating to any infected family members, swabs or serological tests**, so as to have a complete picture of your condition as you would do in front of a doctor.

Could you please confirm or deny the aforementioned statement? 

Is it true? is it false?

Nowhere and nobody has ever been talked about collecting Immuni users' health records and I think this would be a tremendous and unacceptable privacy issue.

Would you care to clarify please?

Thank you in advance, I look forward to reading a statement and a reply from you soon.

**Comment by immuniopensource** [comment]
Hi @p43b1 , Immuni does not collect the information listed by the article you linked. You can read the documentation to find out more about the app. However, in short, the only datum the app asks the user to input is their province of domicile. We hope this helps!
