### ISSUE TITLE
Dummy traffic?

### ISSUE THREAD

**Issue by fbertola** [immuni-app/immuni-documentation#57]
Hello!
In the _Open Points_ section you mention:

> **Dummy traffic.** We would like to minimise the information that an attacker could gain by analysing network traffic. We are finalising decisions on sampling rules and dummy uploads.

Is this kind of measure necessary? From my point of view, Immuni should never be able to communicate the health status of the user; instead, it should be the responsibility of hospitals or family doctors. If this is unavoidable, just send a single message every day, regardless of the positivity. Dummy traffic should be avoided and used only as a last resort, as it will cause unnecessary network pressure and opens the possibility of unforeseen attacks. 

I have no doubt that there is a good reason behind this decision, but nonetheless it's quite rare to see this kind of measure taken. From my experience, I've only seen it implemented in:

- crypto modules/SOC
- P2P protocols
- Secure voice/stream/realtime applications
- VPN protocols or any application that tries to circumvent censorship and detection

Without seeing the rationale —and possibly the analysis— behind this point, I'm worried that it might cause more problems than the one that it's trying to solve.

Thanks!

**Comment by ALBUCHERQUE** [comment]
Their the best of the best in Europe! Have you ever considered that they now better then you?! WHat have you done anyway?!! Are you a security expert? I dont think so! Your just a nobody jealous of their work. I bet you and the other guys who ciritcize them are just people who are not passed of their selection.
Your comment is just cringe. I worked on various military grade security and i can assure you that their metodh is perfect.
Turn back at working in python and dont embarrass yourself anymore.

Ho BTW, we are laughing really hard about all of you on reddit https://www.reddit.com/r/ItalyInformatica/comments/gml03y/immuni_app_name_is_misleading/ :DDD

**Comment by ivanvisconti** [comment]
Dummy traffic can be very important for privacy. Let's wait for the technical documentation explaining the privacy and security guarantees of their system and the role of all tools (dummy traffic included) to achieve them. Hopefully at some point they will provide such details since for now they are providing vague claims only about the features of their system.

**Comment by fbertola** [comment]
I never stated that it is not important. My only concern is that it should be used only if absolutely necessary, especially on an application which tries to reach as many people as possible. Filtering this kind of traffic can only be done on the Application Layer, which is less robust against DDOS attacks.

**Comment by immuniopensource** [comment]
Hi @fbertola. We’re working on a separate document that explains our design choices in detail. The document will be made available in a matter of days. We look forward to receiving feedback on it. Closing this issue for now, thanks for your patience.
