### ISSUE TITLE
Decentralization seems to not be guaranteed 

### ISSUE THREAD

**Issue by vi-enne** [immuni-app/immuni-documentation#59]
In a recent [interview ](https://www.corriere.it/tecnologia/20_maggio_17/app-immuni-paola-pisano-l-ho-scelta-io-assieme-speranza-pronta-entro-maggio-2badf3dc-9881-11ea-ba09-20ae073bed63.shtml) , Innovation Minister Pisano declared

> «Grazie alle elaborazioni fatte sul server di Sogei sapremo in forma anonima e aggregata quanti soggetti sono stati allertati in ogni provincia, quanti poi effettivamente si ammalano, dopo quanto tempo e a quale distanza e in che giorno sono stati a contatto con un infetto».

It seems then that the server will contain information about both the infected user and his/her contacts. Even if the information is read in anonymized and aggregated form, the detailed contacts will be on the server.

Could you please clarify how this guarantees decentralization?

Thank you.

**Comment by gianmoretti** [comment]
Starting from this question, will the source of backoffice tool be available in the future?

**Comment by immuniopensource** [comment]
Good morning @vi-enne, we have updated our documentation and added [Privacy-Preserving Analytics](https://github.com/immuni-app/immuni-documentation/blob/master/Privacy-Preserving%20Analytics.md), which details the information that Immuni discloses as well as how it preserves the user’s privacy. The information shared with the Analytics Service does not disclose the user’s identity. Additionally, Epidemiological Info does not hold any information about whom the user came into contact with or about the contact itself. Should you have any other inquiries, please let us know, thank you.
