### ISSUE TITLE
Ensure that user interface is accessible

### ISSUE THREAD

**Issue by falcon03** [immuni-app/immuni-documentation#61]
While skimming the documentation, I noticed that no statement has been made about the app user interface accessibility, i.e. its ability to be used by people with disabilities who leverage assistive technologies in order to interact with their smartphones.

Other than a law requirement, making the app accessible will ensure that people with disabilities can use it. Both on iOS and Android assistive technology exist that allow people with disabilities to interact with their device: screen reader (talkback on Android, VoiceOver on iOS) for blind people, screen magnifying, switch control for people with motor impairments, etc.

Having more details on which frameworks/technologies will be employed to create the app's user interface would help provide more recommendations in this regard.

**Comment by immuniopensource** [comment]
Dear @falcon03, accessibility has been one of this project’s guiding principles. Immuni is implemented in iOS and Android using native technologies. As a result, Immuni can leverage everything that the operating systems offer out of the box (e.g., high text contrast, color correction).

The iOS client supports Dynamic Type, Reduced Motion, and VoiceOver. The Android client supports Font Size, Display Size, Reduced Motion, TalkBack, and Select To Speak.

The colours were chosen to ensure a sufficient contrast ratio between the text and its background, and care has been taken to ensure that colour is not the only visual means of conveying information.

Should you have any other inquiries or feedback please let us know, thank you!
