### ISSUE TITLE
Provide an implementation of the app not relying on Google Play Services 

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-documentation#62]
An implementation of the app not relying on Google Play Services should be provided for users of AOSP-based devices.
Such implementation of the app, not depending on closed source components, should be made available through open source repositories such as F-Droid.

**Comment by SannitaSSJ** [comment]
Already discussed in #20

**Comment by lmasellis** [comment]
> Already discussed in #20

Better say: not addressed and improperly closed in #20.

Anyway, there is a subtle (but important) difference between removing dependency on Google Play Services and providing an alternative (additional) implementation not relying on Google Play Services.

**Comment by immuniopensource** [comment]
Hi @lmasellis and thanks for your issue. 
Since the aim of this project is to create an app leveraging the G/A APIs, this issue is out of topic here. However, theoretically Immuni could also work with a different but compatible implementation of the G/A APIs.
Let us know if you need more information, thank you for your time.

**Comment by lmasellis** [comment]
You are completely ignoring the fact that, by providing no alternative to Google Play Services, you are pushing users to accept Google terms & conditions and privacy policy.

It's not acceptable for a state sponsored service to be practically bundled with a completely extraneous contractual agreement with a private entity, which cannot be opted out.

In order to use Immuni on an Android device, I am forced to also accept Google's terms and conditions, to create a Google account and to accept Google's privacy policy. This is completely unacceptable and your closure of this report does not address any of these issues.

**Comment by echeoquehaii** [comment]
> Hi @lmasellis and thanks for your issue.
> Since the aim of this project is to create an app leveraging the G/A APIs, this issue is out of topic here. However, theoretically Immuni could also work with a different but compatible implementation of the G/A APIs.
> Let us know if you need more information, thank you for your time.

Dear @immuniopensource could you provide a public explanation about why you don't provide an Android version which is compatible with phones not using the Google Play Services Framework?

Since:
> theoretically Immuni could also work with a different but compatible implementation of the G/A APIs.

**Comment by echeoquehaii** [comment]
> Already discussed in #20

And not solved, but closed.

**Comment by edo0** [comment]
@carallo Not a solution but a workaround, have you tries microG? (De-bloated and more privacy-respecting implementation of the open source bade of Google Play Services - available up to Android 9 as of now if I am not mistaken)

**Comment by lmasellis** [comment]
> @carallo Not a solution but a workaround, have you tries microG? (De-bloated and more privacy-respecting implementation of the open source bade of Google Play Services - available up to Android 9 as of now if I am not mistaken)

MicroG does not provide at the moment an implementation of the Exposure Notification API.

But it seems they are thinking about it:

https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-640014651
