### ISSUE TITLE
Provide a live counter of contacts recorded

### ISSUE THREAD

**Issue by lmasellis** [immuni-app/immuni-documentation#63]
The app should provide the user with a live counter of contacts recorded.

While the number itself is of no real significance (it would not count unique subjects but just ephemeral IDs), the counter would serve as a "hearthbeat", providing the user confidence that the app is actually doing its job. People is going to install this app and, if everything goes well, they will see no feedback at all for months: this could create the false sensation that the app is doing nothing and is not useful. Showing some kind of "progress" can create a sense of community involvement ("See how many! Everybody is using it!").

Of course the UI has to be well thought, so that number of contacts cannot be mistaken as an indication of dangerous contacts.

See for similarity: https://github.com/DP-3T/dp3t-app-android/issues/3

**Comment by immuniopensource** [comment]
Hi @lmasellis,
As much as it could be interesting to some users to have such a feature in place, I am afraid that we will never be able to add it to Immuni—provided that Apple and Google don’t make any significant changes to their Exposure Notification Framework. The collection and storage of Contact information is entirely handled by the A/G Framework, which provides the App with an Exposure Detection Summary and (in the case of Risky Exposures) Exposure Info. Both only contain data about Exposures to potentially contagious users (those who chose to upload their TEKs), not just about any user you may have come into Contact with.
We could show users the count of Exposures, but this would not achieve what you suggest—that is, keep users appraised of the working condition of the App—as such events are expected to be quite infrequent. Moreover, providing such count could raise some privacy concerns.
That said, we want to assure you that we have already taken some measures to make sure you will know if something is not working as expected. The App regularly checks whether it has all the required permissions and if all the services it needs (e.g., Bluetooth) are active. If that is not the case, it sends a local notification that invites you to open it. In the Home section, the App clearly displays whether it is working as intended, and, if not, it guides you through the steps needed to solve the issue.
I hope this clarifies and wish you all the best!

**Comment by lmasellis** [comment]
One more reason to ask not to rely on Google Play Services, because all the actual processing is done in closed source and apps like Immuni will provide just a bare user interface. It makes no sense discussing here about how Immuni works, if it cannot even count how many contacts it recorded. It makes no sense even making the app open source, if the real processing is completely hidden in Google's binaries.

We have gone to the point that private overseas corporations like Google and Apple, not only decide what users are allowed to do with their own devices, but also have the power to impose their own closed software to legitimate governments. We have gone to the point that these corporations self-proclaim themselves as more trustworthy than legitimate governments, and governments have nothing to object about this.
