### ISSUE TITLE
Why is there an exposure summary in the TEK upload?

### ISSUE THREAD

**Issue by ijansch** [immuni-app/immuni-documentation#71]
In the tek upload section of https://github.com/immuni-app/immuni-documentation/blob/master/Technology%20Description.md#backend-services-technologies, it seems that when uploading the TEKs, it includes exposure summary info. Is this to do analytics of who is infected AND has seen an notification before? Does this mean the App remembers the notification?

**Comment by vi-enne** [comment]
From the [Glossary](https://github.com/immuni-app/immuni-documentation/blob/master/Technology%20Description.md#glossary):

> Operational Info. Data on the Mobile Client’s working condition and Exposure notifications. The data include:
> 
> - Whether the device runs iOS or Android
> - Whether permission to leverage the A/G Framework is granted
> - Whether the device’s Bluetooth is enabled
> - Whether permission to send local notifications is granted
> - **Whether the user was notified of a Risky Exposure after the last Exposure Detection**
> - The date on which the last Risky Exposure took place, if any

So, the answer to your question appears to be yes.

**Comment by immuniopensource** [comment]
Good morning @ijansch, as described in [Privacy-Preserving Analytics](https://github.com/immuni-app/immuni-documentation/blob/master/Privacy-Preserving%20Analytics.md), Exposure Detection Summaries and Exposure Info are uploaded when a user who has tested positive for SARS-CoV-2 uploads their TEKs. The A/G framework provides this information which Immuni collects for the sole purpose of optimising the App’s risk model (thus improving its effectiveness). Exposure Detection Summaries and Info are stored after a Risky Exposure is detected and kept for a maximum of 14 days.
The information that @vi-enne referred to is instead sent along with an Operational Info with Exposure, when the app detects a Risky Exposure and alerts the user through a notification.
Let us know if you have any other doubts or questions regarding this issue, thank you for your time!
