### ISSUE TITLE
Changing RPI may defeat the purpose of having accurate duration of Exposure

### ISSUE THREAD

**Issue by vi-enne** [immuni-app/immuni-documentation#73]
This may sound like a petty issue, but I am writing it for the sake of clarity. Feel free to close it if you find it irrelevant

In the [Glossary](https://github.com/immuni-app/immuni-documentation/blob/master/Technology%20Description.md#glossary), you define:

> The duration of the Exposure (measured in five-minute increments and capped at 30 minutes)

and then

> Rolling Proximity Identifier (RPI). A 16-byte identifier generated from a TEK, broadcast via BLE by a Mobile Client, and stored locally by the nearby Mobile Clients. **The RPI being broadcast changes multiple times an hour** to prevent wireless tracking of the Mobile Client.

Assuming that the RPI changes _n_ times an hour, it means that it changes every 60/n minutes on average.
_Multiple times an hour_ implies that the RPI changes at least 2 times per hour.

Now, if n > 2, the time between two changes is less than 30. What is the point of capping the duration of the Exposure at 30 minutes then?

Please, be sure to set a reasonable number of changes per hour (less than 12 on average!).

Thank you and good work.

Edit:
I found [this document](https://blog.google/documents/58/Contact_Tracing_-_Bluetooth_Specification_v1.1_RYGZbKW.pdf) from Google's blog [The Keyword](www.blog.google). On page 3, it states
> **Rolling Proximity Identifier** - A privacy preserving identifier derived from the Daily Tracing Key and sent in the bluetooth advertisements. **It changes every ~15 minutes** to prevent wireless tracking of the device. 

This confirms my understanding that the Duration of the Exposure can never be measured as more than ~15 minutes, so capping it a 30 minutes is useless since the number of changes per hours is greater than 2 (around 4).

Bare in mind that the linked document is labelled as _Preliminary - Subject to Modification and Extension_, so clarification from your part is still needed.

Edit 2:
Your own [Privacy Policy](https://www.immuni.italia.it/app-pn.html) states: 
"Ogni 10 minuti Immuni genera un codice casuale (Rolling Proximity Identifier - RPI) a partire dalla chiave di esposizione giornaliera (Temporary Exposure Key - TEK) e lo invia ai dispositivi vicini"

So the number of changes _n_ appear to be 6.

How is this coherent with the idea that a contact is at risk if longer than 15 minutes?
See [here](https://www.corriere.it/tecnologia/20_giugno_01/immuni-come-scaricare-l-app-quando-come-usarla-e25aa3f6-a424-11ea-b19d-c124828d4b5b_amp.html) or [here](https://www.google.com/amp/s/www.ilmessaggero.it/AMP/italia/coronavirus_italia_fase_2_lockdown_arcuri_contagio_news-5197168.html) for example.

**Comment by immuniopensource** [comment]
Hi @vi-enne. It is true that RPI rotates every ~15 minutes. However, a user testing positive for SARS-CoV-2 doesn’t upload their RPIs to the server. Instead, they upload their Temporary Exposure Keys (TEKs), from which the RPIs are deterministically generated. This ensures that a user who has been exposed to a positive contact can link two different RPIs to the same user, thus considering it as the same contact. Therefore, the theoretical cap on the maximum continuous exposure is actually 24 hours (i.e., the validity period of a single TEK). That said, the Apple/Google framework does not provide Immuni with the raw duration of the exposure, but it reports it in 5-minute increments and caps it at 30 minutes to preserve the user’s privacy.

We're closing this issue, but feel free to reopen it if you have additional doubts. Thank you!
