### ISSUE TITLE
### Traffic-analysis mitigation

### ISSUE THREAD

**Issue by vastianazzo** [immuni-app/immuni-documentation#80]
Dalla documentazione
Without appropriate countermeasures, even if the data in transit are encrypted, an attacker could still infer sensitive information by analysing the communication between the Mobile Client and Backend Services. For example, an exchange of information between the Mobile Client and the Exposure Ingestion Service could reveal that the user is uploading their TEKs and has therefore tested positive for SARS-CoV-2. To minimise this risk, the following measures are in place:
- Mobile Clients regularly send dummy requests

Visto che è possibile un’analisi del traffico, la misura di pacchetti fasulli inviati al server non è idonea alla mitigazione del rischio, poichè tale misura ha un senso nel caso in cui l’upload dei dati avvenga sempre all’interno dello stesso network. Cosa che, invece, sarà improbabile. Infatti è altamente probabile che l’eventuale invio dei dati avvenga all’interno di una struttura sanitaria, una volta che è stato comunicata la positività al COVID. Ciò esporrà l’utente al fatto che, mediante l’analisi del traffico, sarà facilmente identificabile il soggetto che effettua l’upload dei dati connesso all’interno del network aziendale della struttura sanitaria. 
Dovrebbe essere prevista un avviso, in modo da informare l’utente, per esempio, di effettuare l’upload solamente tramite la connessione dati e disconnettendo la connessione wireless.

**Comment by immuniteam** [comment]
Hello @vastianazzo, data uploading does not necessarily take place as you say within the network of a healthcare facility. Indeed, it is likely that users will use their data connection or the WiFi to which they are connected when the result of the virus positive test is communicated by telephone.
Furthermore, the dummy traffic mechanism is designed to work independently of the network to which a user who uses Immuni is connected and uses a probabilistic approach which, by its nature, makes it impossible for an attacker to obtain certain information regarding the nature of the communication between clients and servers. Let us know if you need further details, for the moment we close the issue.
