### ISSUE TITLE
Add button "Share app"

### ISSUE THREAD

**Issue by matteoloduca** [immuni-app/immuni-documentation#86]
I think is a good idea add button like "Share App" or "Tell a friend" to increase the usage of app.

**Comment by gbonfiglio** [comment]
StopCovid (France App) is doing that, pointing to a landing at https://bonjour.stopcovid.gouv.fr/

Text reads:
`I’m using StopCovid to fight the pandemic, to send and receive information. You should install the app too: https://bonjour.stopcovid.gouv.fr/`

It's probably a good idea.

**Comment by immuniopensource** [comment]
Thank you for the suggestion, @matteoloduca. We implemented it and released it with the 1.3.0 update. You can find it within the `Settings` tab.
Let us know if you have any other doubts, thank you!
