### ISSUE TITLE
Statistiche d’uso

### ISSUE THREAD

**Issue by antonellopasella** [immuni-app/immuni-documentation#90]
Mostrare all’utente quante volte e per quanto tempo è stata “vicino” a qualcuno con l’app attiva.

Sarebbe utile per dare una reale percezione della diffusione dell’app anche all’utente finale, in forma di dati aggregati per salvaguardare privacy dei “vicini”

**Comment by vi-enne** [comment]
La questione è stata trattata in #63. Magari la risposta data da @immuniopensource può esserle utile :)
