### ISSUE TITLE
Maggiore informazione su come gli utenti possono comunicare infezione

### ISSUE THREAD

**Issue by tmontanaro** [immuni-app/immuni-documentation#91]
Non è chiaro, installando e aprendo l'app in che modo una persona possa comunicare di essere o essere stata infetta.
Inoltre, qualora (come credo) sarà l'ASL a comunicarlo al sistema) non è nemmeno chiaro se la persona potrà autorizzare la "diffusione" della news in un secondo momento. Cioè, il centro analisi mi dice che sono positivo e io in quel momento non voglio che lo comunichi. Poi però a distanza di qualche giorno cambio idea: come faccio a comunicarlo? Ovviamente servirà qualche protezione per evitare che altri premano il pulsante al mio posto?

**Comment by ItsFiloHere** [comment]
Come puoi notare nell'app, i dati possono essere inviati solamente con l'aiuto di un operatore autorizzato. Come riportato dal Ministero della salute in [questa circolare](http://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2020&codLeg=74178&parte=1%20&serie=null) "Quando un utente risulta SARS-CoV-2 positivo, l’operatore sanitario che gli ha comunicato l’esito
del test diagnostico gli chiede se ha scaricato l’app e lo invita a selezionare sul proprio smartphone
l’opzione per il trasferimento delle sue chiavi anonime nel sistema del Ministero della salute. L’app
restituisce un codice numerico (OTP) che l’utente comunica all’operatore sanitario. Il codice viene
inserito, da parte dell’operatore sanitario, all’interno di un’interfaccia gestionale dedicata,
accessibile per il tramite del Sistema Tessera Sanitaria, e il caricamento viene confermato
dall’utente".
Riguardo la tua domanda, non saprei dirti se puoi cambiare idea sul caricamento, qui dovresti chiedere o all'assistenza di Immuni (800 91 24 91, tutti i giorni dalle 8 alle 20) o alla tua ASL (quando il sistema sarà attivo in tutte le regioni).

**Comment by immuniopensource** [comment]
Buongiorno @tmontanaro. 
Come riportato da @filioro, non è l’ASL a comunicare la positività al sistema, ma l’utente stesso, attraverso la funzione “Segnala positività” presente nella tab “Impostazioni”. L’operazione richiede il supporto di un operatore sanitario, il quale autentica l’OTP generato dall’utente, abilitando così il caricamento delle chiavi crittografiche associate al proprio dispositivo. 
Può succedere che tu decida di non caricare i tuoi dati, salvo poi cambiare idea a distanza di ore o giorni. In questo caso, ti invitiamo a contattare direttamente la tua ASL e fargli presente la tua situazione.
Se dovessi avere altri dubbi restiamo a disposizione, grazie!
