### ISSUE TITLE
Urgent: make the app not dependant on Google Play Services Framework/Huawei Mobile Framework

### ISSUE THREAD

**Issue by echeoquehaii** [immuni-app/immuni-documentation#92]
I am really really baffed by the need of Google Play Services on our phones to make this app work.
This app is fundamental in the tracing and control of a world epidemics and it cannot work if not using such proprietary frameworks.

I have tried the Norwegian COVID tracing app and it works without issues at all without Google Play Services, this means that it's not a problem of technology but of will, of making the app available on phones which don't have the Play Services installed, which are many.
Health prevention and epidemics control cannot rely on proprietary frameworks which are completely out of control. This means that PUBLIC HEALTH depends on the decisions of a private company which might change things whenere they want and THIS IS NOT ACCEPTABLE!

**Comment by vi-enne** [comment]
An answer, even if not satisfying for the OP, was given in #62

**Comment by echeoquehaii** [comment]
> An answer, even if not satisfying for the OP, was given in #62

And in #20 , and they are not satisfying at all.

Since the other issue has been closed and I is fundamental to raise the topic I will write it here too:

While it might be indeed true that the market share of phones without Google Play Services Framework might be very low, this doesn't imply that the app NEEDS to rely on it.
As a pure example, the Norwegian COVID tracing app dosen't rely on Play Services, can be downloaded directly from the Health Ministry webpage and works flawlessly.
This means that the decision of making the app dependant on the A/G Framework is purely political and based on the agreements made with such companies, but is not at all necessary for the functioning of the app.

The problem with saying that the number of people not having Play Services is very low is that it shows complete disrespect for such people. It might not be relevant from a statistical point of view for the aggregate data and epidemics control, but it is FUNDAMENTAL that people are given the right and means to know if they have been in contact with any infected person. I, as an individual, take care of my health and try to protect myself and my own family and social circle from getting the virus. The government's sponsored app doesn't allow me to do that because of political reasons.

I AM DISGUSTED and VERY VERY ANGRY, also by the disrespect and superficiality showed by the replies of some users and developers.

EDIT: the same concerns have been raised by the European Commission itself [here](https://eit.europa.eu/news-events/news/european-struggle-covid-19-contact-tracing-apps). Just follow their recommendations!

**Comment by FredBonux** [comment]
Hi, first of all, I would ask to calm down and to avoid terms like "DISGUSTED" as in GitHub, usually, people try to solve problems not to insult or take sides.

Second, Google + Apple API seems to work really well together, and as those APIs are mandatory in Apple's operating system, using the same API on Android looks like a logical solution. Also, Google (as others) has access to the OS resources directly (via Play Services), so any API made by the OS owner will be more reliable, more efficient, and more effective than any "custom" app-based API.

Third, the Norwegian COVID app also has its own problems (see [this](https://www.digi.no/artikler/stromsluk-problemet-til-smittestopp-appen-er-trolig-lost/490243) and [this](https://nrkbeta.no/2020/04/20/sa-enkelt-er-det-a-forfalske-sms-er-fra-smittestopp/) via [this article](https://www.lifeinnorway.net/smittestopp-coronavirus-app/)), and in fact, does not work (well) on iOS devices (as it is required to keep the app in foreground to use the Bluetooth)

Finally, the European Commission raised some concerns because, once again, Europe is behind and heavily depends on American corporations in order to make things work, but this is another topic, not related to "Immuni".

**Comment by echeoquehaii** [comment]
Hello,

I know how GitHub works and sorry if someone might have felt offended by my words. Of course my disgust was not related to any person in particular, but to the situation in general which has been generated by a system in which two major companies can dictate which technologies and how to use them in a issue such as this one, where a global pandemic must be monitored and controlled.
And while writing these words my blood pressure goes up again, since the importance of the issue. Sorry for that.

> Finally, the European Commission raised some concerns because, once again, Europe is behind and heavily depends on American corporations in order to make things work, but this is another topic, not related to "Immuni".

Totally agree, but Immuni is one of those apps and it could try to use other technologies instead of using the G/A APIs, or at least give the chance to have a "Google Play Services free" version, like it happens with many other apps. Easy? No, but the right thing to do, and not impossible. Also this concerns the problem of using the app in devices which are not supported by the framework, which are not necessarily "Tinfoil Geeks" or similar, but just people using Xiaomi's phones, slightly old phones and so on...

> Third, the Norwegian COVID app also has its own problems (see this and this via this article), and in fact, does not work (well) on iOS devices (as it is required to keep the app in foreground to use the Bluetooth)

Of course it has issues but at least it can be installed more freely and those issues, as you can see, are again probably due to Apple and Google policies. For example the "Heavy power consumption" on Android is a known issue for apps which don't use the Google Cloud Messaging framework to provide notifications. While, as you said, "those APIs are mandatory in Apple's operating system". It's true that developers cannot do anything about this, but it still confirms what you also said, that those companies have such power to be able to influence critical decisons such as this one about a pandemic tracing app. Apple can freely decide that people with an old version of software cannot track their contacts with infected people and thus cannot protect themselves or their relatives from getting sick. Not for technological limits, but the policies of a random private company. This is what makes me go nuts.
But while this is something the developers cannot do nothing about, at least the Android system gives more flexibility.

> in GitHub, usually, people try to solve problems

This is what I was referring to "the replies of some users and developers". I have gone through the other bugs opened about this issue and have not seen any reply which implied at least that the point had been taken in consideration and an evaluation on the case had been made. The idea of making an Android app which could have the possibility of being used also without the Google Services Framework has never been taken in account, no idea or workaround has ever been proposed, the answer is always implicitly been "the app must use the G/A API, that's it".

That's not how GitHub, usually, works.

That's why I'm opening an issue and would like it to be discussed and solved.
But, as previously said:  
> An answer, even if **not satisfying** for the OP, was given

And the issues were closed...

**Comment by echeoquehaii** [comment]
I link here the source code of the french app, which indeed works on all phones with no Google Services limitations:

[StopCovid FR](https://gitlab.inria.fr/stopcovid19/stopcovid-android)

This should serve as proof and encourage the Immuni developers to discuss what the limitations of such implementation are and why they are not willing to take that approach.

@immuniopensource , as in #101 a clearer clarification of the roles of the developers would be appreciated, especially since this is a government-sponsored project, transparency is crucial.

**Comment by Aerendir** [comment]
UK government sold covid-19 related data and they are not using the covid-19 dedicated APIs.

The use of these APIs is mandatory to guarantee the safety of the data collected and the transparency of the way they are collected.

**Comment by echeoquehaii** [comment]
> UK government sold covid-19 related data and they are not using the covid-19 dedicated APIs.
> 
> The use of these APIs is mandatory to guarantee the safety of the data collected and the transparency of the way they are collected.

You guarantee transparency with an API bundled in a proprietary framework and a proprietary OS?
