### ISSUE TITLE
[GENERAL] Documentazione in italiano

### ISSUE THREAD

**Issue by albertotn** [immuni-app/immuni-documentation#97]
# Issue content

Sarebbe auspicabile che i repository del progetto Immuni avessero dei README ( non il codice ) in italiano, così da facilitarne la comprensione anche a noi non tecnici o ai curiosi ( soprattutto visto il tema in oggetto)

**Comment by Stormur** [comment]
Focus anche su:

> The application itself, documentation and all end-user facing content will - **of course** - be made available in German (and probably other languages as well)

**Comment by FredBonux** [comment]
> Focus anche su:
> 
> > The application itself, documentation and all end-user facing content will - **of course** - be made available in German (and probably other languages as well)

@Stormur
Note that what they call "documentation" in that phrase is the actual copy that explains how the system works. They call "developer documentation" the technical docs. 
In "Immuni", the app, the "docs", and all end-user facing content are already available in Italian, English, German and French. ToS and Privacy Policy are coming with multi-language support while right now they are only available in Italian.

**Comment by immuniopensource** [comment]
Hi @albertotn, as some other members already mentioned we will use English as the lingua franca for this repository so a translated version of the documents is not planned. Thank you for your time, I'm closing this issue for now.
