### ISSUE TITLE
No representation of minorities in the app drawings

### ISSUE THREAD

**Issue by Qosw34** [immuni-app/immuni-documentation#99]
As the title reads, I find it disheartening that not a single drawing in immuni seems to portray minorities. Regrettably, only white people are featured. This is particularly unfortunate in this day and age, as lack of minority representation in such a high-profile app as immuni seems to perpetuate stereotypical views that it is on white people only to take on the responsibility of restraining COVID-19 while, say, the black community is apparently uncapable/unwilling of doing that. I urge developers to make up for this shortcomining and change the app drawings so as to allow for minority representation. Thank you! 

![how_it_works_2](https://user-images.githubusercontent.com/66376810/83658690-d8566300-a5c2-11ea-9167-8f2c757d6932.png)
![how_it_works_5](https://user-images.githubusercontent.com/66376810/83659004-46028f00-a5c3-11ea-8183-26f2c08ce30e.png)
![welcome_1](https://user-images.githubusercontent.com/66376810/83659009-48fd7f80-a5c3-11ea-9e28-fd46988ec3b4.png)
![welcome_2](https://user-images.githubusercontent.com/66376810/83659236-8eba4800-a5c3-11ea-98a6-8c35d0edfd28.png)
![illustration_person](https://user-images.githubusercontent.com/66376810/83659251-92e66580-a5c3-11ea-887b-5b9a8941c78d.png)
![illustration_doctor](https://user-images.githubusercontent.com/66376810/83659258-95e15600-a5c3-11ea-8530-50c347ffd704.png)

**Comment by FredBonux** [comment]
Hi, did you check the homepage of the immuni website?
![image](https://user-images.githubusercontent.com/32730856/83689337-25e8c500-a5ef-11ea-966a-c693de326e97.jpeg)

**Comment by Qosw34** [comment]
Hello @FredBonux, thank you for your consideration. 

While immuni's website is certainly commendable, I was specifically talking about the app. It is immuni's app that the Italian citizens were recommended by their government to download and use. I think that for most Italians immuni is an app. An app which features only drawings of white people.

I'm not trying to give you a hard time, but can you imagine a minority downloading and installing the app just to find that **not a single** drawing is like them, as if they were not considered part of the nation-wide effort to stop COVID-19? It is not pleasant. 

I guess that it won't take you too long to include minority representation in the app (mirroring your beautiful website).

**Comment by ContExpo** [comment]
Yeah, that's absolutely the point of the app.
Please, go ditching ditches or something

**Comment by Qosw34** [comment]
Hi @ContExpo. I'm not saying that diversity should be the point of the app, am I? 

Recently, a controversy was sparked by the stereotypical representation of women portrayed in one of immuni's drawings. You can find more about it [here](https://github.com/immuni-app/immuni-documentation/issues/88). As a result, immuni's developers promptly modified it, kudos to them. Did they do it because they thought diversity the "point of the app"? I don't think so.

Take a look at the contact-tracing apps developed in other countries, for example France (StopCovid) and Australia (COVIDSafe). 


![fr](https://user-images.githubusercontent.com/66376810/83887389-a7079f80-a748-11ea-9af0-cbddf91977cd.png)

![covidsafe-composite-custom-1-data](https://user-images.githubusercontent.com/66376810/83887397-aa029000-a748-11ea-85d4-c19e0739be63.jpg)


They clearly feature diversity, immuni doesn't. Why?

**Comment by immuniopensource** [comment]
Hi @Qosw34 and thanks for your feedback. We’d like to point out that Immuni already features minorities in its drawings, for instance in two of the onboarding screens and in the Exposure Notification permission screen. In any case, in its next version the app will include even more references to minorities to better convey its message of inclusivity. Thanks a lot for raising this very important issue. We're closing this for now, let us know if you need further details. :+1:
